import type { CaseDefinition } from './types.js';
import { hyperkalemiaOverrides } from '../engine/index.js';

/** Group D — mimics (controles negativos). docs/CASES.md §D. */
export const GROUP_D: CaseDefinition[] = [
  {
    id: 'D01',
    group: 'D',
    title: 'Repolarización precoz',
    difficulty: 2,
    vignette: {
      age: 24,
      sex: 'M',
      history: 'Varón de 24 años con dolor pleurítico. ECG con STE cóncavo y muesca en J.',
      vitals: 'PA 120/75, FC 62',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 401,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 62 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.12, refLead: 'V3', shape: 'concave', hyperacuteT: 0 },
      ],
      beatOverrides: { jNotchMv: 0.06, aTScale: 1.3, qtc: 380, rScale: 1.4 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'smith-4v', 'hyperacute-t'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La RP tiene STE cóncavo, muesca en J y R altas en V4.',
      'Smith 4v suele ser negativo en RP por la R alta y el QTc corto.',
      'Puede cumplir criterios STEMI técnicos: el contexto decide.',
    ],
    pitfalls: ['STE técnico en V2–V3 no es oclusión si hay J-notch y concavidad.'],
    refs: [66, 67, 75],
  },
  {
    id: 'D02',
    group: 'D',
    title: 'Pericarditis',
    difficulty: 2,
    vignette: {
      age: 31,
      sex: 'M',
      history: 'Varón de 31 años con dolor postural que mejora al inclinarse.',
      vitals: 'PA 120/80, FC 78',
      troponin: 'hs-cTnT 40 ng/L',
    },
    scenario: {
      seed: 402,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 78 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.05, refLead: 'V3', shape: 'concave' },
        { territory: 'inferior-lcx', st: 0.05, refLead: 'II', shape: 'concave' },
        { territory: 'lateral', st: 0.03, refLead: 'V6', shape: 'concave' },
      ],
      beatOverrides: { prDepressionMv: 0.08 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'STE difuso cóncavo + depresión del PR + ausencia de recíproca = pericarditis.',
      'El STE de pericarditis no respeta un territorio vascular.',
      'aVR sin STE ayuda frente a isquemia subendocárdica.',
    ],
    refs: [75],
  },
  {
    id: 'D03',
    group: 'D',
    title: 'HVI con strain',
    difficulty: 2,
    vignette: {
      age: 70,
      sex: 'F',
      history: 'Mujer de 70 años, hipertensa, con disnea. Voltajes altos y T discordante lateral.',
      vitals: 'PA 165/95, FC 84',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 403,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 84 },
      conduction: 'lvh-strain',
      sources: [],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss:
        'El strain de HVI produce STE discordante proporcional en V1–V3 que cumple umbrales UDMI4; la desproporción ST/QRS (discordancia proporcional) no está codificada como regla, por lo que omi-composite da un falso positivo deliberado.',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El strain de HVI produce STE discordante proporcional en V1–V3.',
      'La desproporción ST/QRS distingue strain de oclusión.',
      'La historia (HTA, voltajes) orienta el diagnóstico.',
    ],
    refs: [16, 76],
  },
  {
    id: 'D04',
    group: 'D',
    title: 'LBBB sin isquemia',
    difficulty: 2,
    vignette: {
      age: 78,
      sex: 'M',
      history: 'Varón de 78 años con LBBB crónico, chequeo sin dolor.',
      vitals: 'PA 135/80, FC 72',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 404,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'lbbb',
      sources: [],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['sgarbossa', 'sgarbossa-modified', 'barcelona', 'omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El LBBB tiene discordancia fisiológica proporcional al QRS.',
      'Sgarbossa y BARCELONA son negativos sin isquemia.',
      'El exceso de discordancia (ST/S) es lo que delata la OMI.',
    ],
    refs: [61, 62],
  },
  {
    id: 'D05',
    group: 'D',
    title: 'Hiperpotasemia',
    difficulty: 2,
    vignette: {
      age: 60,
      sex: 'M',
      history: 'Varón de 60 años con ERC; K+ 7.2. T picudas estrechas y QRS ensanchado.',
      vitals: 'PA 140/85, FC 70',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 405,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'normal',
      sources: [],
      beatOverrides: hyperkalemiaOverrides(),
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'hyperacute-t'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La T hiperkalemia es estrecha y simétrica; la hiperaguda de OMI es ancha.',
      'El score hyperacute-t pondera el área T/QRS: la T estrecha puntúa bajo.',
      'Correlacionar con K+ sérico y ancho de QRS.',
    ],
    refs: [77],
  },
  {
    id: 'D06',
    group: 'D',
    title: 'Brugada tipo 1',
    difficulty: 3,
    vignette: {
      age: 42,
      sex: 'M',
      history: 'Varón de 42 años con síncope. STE en coved V1–V2 con T negativa.',
      vitals: 'PA 125/80, FC 75',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 406,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 75 },
      conduction: 'normal',
      sources: [
        { territory: 'anteroseptal', st: 0.2, refLead: 'V1', shape: 'convex', tInversion: 1 },
      ],
      acquisition: { placement: 'v1v2-high' },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss:
        'La morfología coved con STE ≥ umbral en V1–V2 es indistinguible del STEMI anterior por criterios UDMI4: el diagnóstico de Brugada es clínico-electrocardiográfico (T negativa, V1–V2 altos), no de reglas de oclusión.',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El coved de Brugada desciende a T negativa sin recíproca inferior.',
      'La colocación alta de V1–V2 desenmascara el patrón.',
      'El síncope + Brugada tipo 1 tiene implicaciones de riesgo propias.',
    ],
    refs: [78],
  },
  {
    id: 'D07',
    group: 'D',
    title: 'Takotsubo',
    difficulty: 3,
    vignette: {
      age: 67,
      sex: 'F',
      history: 'Mujer de 67 años tras estrés emocional intenso. STE anteroapical e inferior leve.',
      vitals: 'PA 110/70, FC 96',
      troponin: 'hs-cTnT 140 ng/L',
    },
    scenario: {
      seed: 407,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 96 },
      conduction: 'normal',
      sources: [
        { territory: 'anteroapical', st: 0.15, refLead: 'V4', shape: 'concave' },
        { territory: 'inferior-lcx', st: 0.08, refLead: 'II', shape: 'concave' },
      ],
      beatOverrides: { qtc: 500 },
    },
    expected: {
      omi: false,
      activateCathLab: true,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss: 'Indistinguible de OMI por ECG: la angiografía (sin culpable) es el diagnóstico.',
    },
    angiography: 'coronarias limpias; ventriculografía apical balón',
    teachingPoints: [
      'Takotsubo puede cumplir criterios STEMI: angiografía inmediata.',
      'El QTc prolongado y la discordancia edad/severidad son pistas.',
      'Diagnóstico de exclusión tras coronariografía.',
    ],
    refs: [79],
  },
  {
    id: 'D08',
    group: 'D',
    title: 'Miocarditis',
    difficulty: 2,
    vignette: {
      age: 28,
      sex: 'M',
      history: 'Varón de 28 años tras cuadro viral. STE concavo difuso con PVCs ocasionales.',
      vitals: 'PA 125/80, FC 88',
      troponin: 'hs-cTnT 350 ng/L',
    },
    scenario: {
      seed: 408,
      durationS: 5,
      rhythm: { type: 'pvc', hrBpm: 85, pvcPerMin: 4 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.06, refLead: 'V3', shape: 'concave' },
        { territory: 'lateral', st: 0.05, refLead: 'V6', shape: 'concave' },
      ],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La miocarditis difusa produce STE concavo multiterritorial.',
      'La troponina alta con ECG difuso no es oclusión focal.',
      'La RM cardiaca confirma el diagnóstico.',
    ],
    refs: [75],
  },
  {
    id: 'D09',
    group: 'D',
    title: 'Embolia pulmonar',
    difficulty: 3,
    vignette: {
      age: 50,
      sex: 'F',
      history: 'Mujer de 50 años con disnea súbita. Taquicardia, T negativas V1–V3 (S1Q3T3).',
      vitals: 'PA 100/65, FC 115, SatO2 90 %',
      troponin: 'hs-cTnT 60 ng/L',
    },
    scenario: {
      seed: 409,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 115 },
      conduction: 'rbbb',
      sources: [{ territory: 'rv', st: 0.015, refLead: 'V1', shape: 'concave', tInversion: 0.8 }],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss:
        'S1Q3T3 + BRD de derechas produce un patrón pseudo-Aslanger (STE III aislado, STD lateral, STE en V3R–V4R por discordancia de la BRD) que cumple umbrales UDMI4 en las derivaciones derechas: la regla no discrimina la discordancia propia de la BRD.',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La sobrecarga aguda del VD da T negativas en V1–V3 y BRD incompleto.',
      'Disnea + taquicardia + S1Q3T3 orientan a TEP, no a OMI.',
      'La angio-TC confirma; el ECG solo sugiere.',
    ],
    refs: [80],
  },
  {
    id: 'D10',
    group: 'D',
    title: 'Aneurisma VI (STE persistente)',
    difficulty: 3,
    vignette: {
      age: 66,
      sex: 'M',
      history: 'Varón de 66 años con IAM anterior hace 2 años. STE persistente con Q patológicas.',
      vitals: 'PA 130/80, FC 76',
      troponin: 'hs-cTnT 16 ng/L',
    },
    scenario: {
      seed: 410,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 76 },
      conduction: 'normal',
      sources: [
        {
          territory: 'anterior',
          st: 0.08,
          refLead: 'V3',
          shape: 'straight',
          qLoss: 1,
          tInversion: 0.3,
        },
      ],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pathological-q'],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'DA crónica con aneurisma apical',
    teachingPoints: [
      'El STE persistente con Q patológicas y baja relación T/QRS sugiere aneurisma.',
      'La amplitud T baja respecto al STE distingue aneurisma de OMI aguda.',
      'Comparar con ECGs antiguos es esencial.',
    ],
    refs: [81],
  },
  {
    id: 'D11',
    group: 'D',
    title: 'Hipotermia (Osborn)',
    difficulty: 2,
    vignette: {
      age: 55,
      sex: 'M',
      history: 'Varón de 55 años con hipotermia (T 29 °C). Ondas J en V3–V6 y temblor.',
      vitals: 'PA 110/70, FC 45, T 29 °C',
      troponin: 'hs-cTnT 30 ng/L',
    },
    scenario: {
      seed: 411,
      durationS: 5,
      rhythm: { type: 'sinus-bradycardia', hrBpm: 45 },
      conduction: 'normal',
      sources: [{ territory: 'lateral', st: 0.06, refLead: 'V4', shape: 'concave' }],
      beatOverrides: { osbornMv: 0.25 },
      acquisition: { emg: { sigmaMv: 0.08 }, baselineWander: { amplitudeMv: 0.2, hz: 0.3 } },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La onda J de Osborn es una deflexión positiva justo tras el QRS.',
      'Bradicardia + temblor (artefacto EMG) completan el cuadro.',
      'El recalentamiento resuelve el ECG; no hay oclusión.',
    ],
    refs: [82],
  },
  {
    id: 'D12',
    group: 'D',
    title: 'WPW',
    difficulty: 2,
    vignette: {
      age: 33,
      sex: 'F',
      history: 'Mujer de 33 años con palpitaciones. PR corto y onda delta.',
      vitals: 'PA 115/75, FC 78',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 412,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 78 },
      conduction: 'wpw',
      sources: [],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'WPW: PR corto + onda delta + T discordante secundaria.',
      'La discordancia por preexcitación no es isquemia.',
      'La historia de palpitaciones orienta el diagnóstico.',
    ],
    refs: [82],
  },
  {
    id: 'D13',
    group: 'D',
    title: 'Atleta',
    difficulty: 2,
    vignette: {
      age: 22,
      sex: 'M',
      history: 'Varón de 22 años, atleta, en chequeo. Bradicardia con STE cóncava V2–V4.',
      vitals: 'PA 110/70, FC 46',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 413,
      durationS: 5,
      rhythm: { type: 'sinus-bradycardia', hrBpm: 46 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.1, refLead: 'V3', shape: 'concave' }],
      beatOverrides: { aTScale: 1.2, qtc: 380 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'hyperacute-t'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El atleta joven muestra RP con bradicardia y T amplias.',
      'La T grande del atleta es ancha pero no hiperaguda (área/QRS normal).',
      'El contexto de chequeo sin síntomas descarta OMI.',
    ],
    refs: [75],
  },
  {
    id: 'D14',
    group: 'D',
    title: 'Inversión LA‑RA',
    difficulty: 1,
    vignette: {
      age: 60,
      sex: 'M',
      history:
        'Varón de 60 años derivado por «IAM lateral» en triage. ECG con I invertida y aVR positiva.',
      vitals: 'PA 130/80, FC 72',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 414,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'normal',
      sources: [],
      acquisition: { placement: 'la-ra-swap' },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'stemi-udmi4'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'LA-RA invertidos: I negativa, aVR positiva, precordiales normales.',
      'El artefacto de electrodos es el mimics más barato de corregir.',
      'Repetir el ECG con colocación correcta antes de decidir.',
    ],
    refs: [99],
  },
];
