import type { CaseDefinition } from './types.js';

/** Group A — oclusión evidente (STEMI+). docs/CASES.md §A. */
export const GROUP_A: CaseDefinition[] = [
  {
    id: 'A01',
    group: 'A',
    title: 'DA proximal clásica',
    difficulty: 1,
    vignette: {
      age: 58,
      sex: 'M',
      history:
        'Varón de 58 años con dolor torácico opresivo de 40 minutos de evolución, irradiado a brazo izquierdo, con diaforesis intensa. Sin antecedentes cardiovasculares conocidos.',
      vitals: 'PA 140/85, FC 92, SatO2 97 %',
      troponin: 'hs-cTnT 45 ng/L',
      symptomsOnsetMin: 40,
    },
    scenario: {
      seed: 101,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 92 },
      conduction: 'normal',
      sources: [
        { territory: 'anteroseptal', st: 0.35, refLead: 'V2', shape: 'convex', hyperacuteT: 0.8 },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 40,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: ['wellens', 'avr-diffuse-std', 'reciprocal-avl', 'rv-involvement'],
    },
    angiography: 'DA proximal TIMI 0',
    teachingPoints: [
      'El STE convexo en V1–V4 con STD inferior recíproca orienta a DA proximal.',
      'La reciprocidad inferior aumenta la especificidad del STE anterior.',
      'La activación precoz del código infarto reduce el tiempo de reperfusión.',
      'En varón <50–60 años el umbral UDMI4 de 2 mm en V2–V3 ya es muy específico cuando la morfología es convexa.',
    ],
    pitfalls: [
      'Confundir con repolarización precoz si el STE es sutil.',
      'Confundir con repolarización precoz si el STE es sutil.',
      'Descartar el infarto por troponina inicial negativa.',
      'No registrar la evolución en los primeros minutos.',
    ],
    refs: [1, 5, 7],
  },
  {
    id: 'A02',
    group: 'A',
    title: 'DA media',
    difficulty: 1,
    vignette: {
      age: 66,
      sex: 'F',
      history:
        'Mujer de 66 años con dolor torácico de 2 horas de evolución y disnea progresiva. Refiere náuseas y palpitaciones.',
      vitals: 'PA 130/80, FC 100, SatO2 95 %',
      troponin: 'hs-cTnT 320 ng/L',
      symptomsOnsetMin: 120,
    },
    scenario: {
      seed: 102,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 96 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.25, refLead: 'V3', shape: 'straight' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 120,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA media',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: ['avr-diffuse-std'],
    },
    angiography: 'DA media TIMI 0',
    teachingPoints: [
      'A las 2 h el STE es franco y puede empezar a desarrollarse onda Q.',
      'El STE en V2–V5 localiza la lesión en la DA media.',
      'La troponina elevada no retrasa la reperfusión.',
      'La disnea progresiva con dolor de larga evolución orienta a territorio anterior extenso.',
    ],
    pitfalls: [
      'Atribuir la disnea a otra causa y demorar la angiografía.',
      'No repetir el ECG ante síntomas persistentes.',
    ],
    refs: [1, 5],
  },
  {
    id: 'A03',
    group: 'A',
    title: 'CD con BAV completo',
    difficulty: 2,
    vignette: {
      age: 71,
      sex: 'M',
      history:
        'Varón de 71 años con síncope súbito e hipotensión. FC muy baja al ingreso, con respuesta pobre a atropina.',
      vitals: 'PA 80/50, FC 38, SatO2 94 %',
      troponin: 'hs-cTnT 180 ng/L',
    },
    scenario: {
      seed: 103,
      durationS: 5,
      rhythm: { type: 'av-block-3', atrialBpm: 80, escapeBpm: 38, escapeWide: true },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-rca', st: 0.3, refLead: 'III', shape: 'straight' },
        { territory: 'rv', st: 0.15, refLead: 'V4R', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 90,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD proximal',
      positiveFindings: ['stemi-udmi4', 'rv-involvement', 'reciprocal-avl'],
      negativeFindings: ['de-winter', 'aslanger'],
    },
    angiography: 'CD proximal TIMI 0',
    teachingPoints: [
      'El BAV completo en IAM inferior indica CD proximal (nodo AV irrigado por CD).',
      'La afectación del VD se confirma con V4R y explica la hipotensión.',
      'Evitar nitratos en el infarto de VD.',
      'La hipotensión con ingurgitación sin edema pulmonar sugiere afectación del ventrículo derecho.',
    ],
    pitfalls: [
      'Administrar nitratos o diuréticos ante la hipotensión del VD.',
      'Interpretar la bradicardia como efecto vagal benigno.',
    ],
    refs: [48, 54],
  },
  {
    id: 'A04',
    group: 'A',
    title: 'CD con bradicardia y VD',
    difficulty: 2,
    vignette: {
      age: 63,
      sex: 'F',
      history:
        'Mujer de 63 años con náuseas, vómitos e hipotensión. Ingurgitación yugular sin edema pulmonar.',
      vitals: 'PA 85/50, FC 48, SatO2 96 %',
      troponin: 'hs-cTnT 95 ng/L',
    },
    scenario: {
      seed: 104,
      durationS: 5,
      rhythm: { type: 'sinus-bradycardia', hrBpm: 48 },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-rca', st: 0.2, refLead: 'III', shape: 'straight' },
        { territory: 'rv', st: 0.12, refLead: 'V4R', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD proximal',
      positiveFindings: ['stemi-udmi4', 'rv-involvement'],
      negativeFindings: ['aslanger'],
    },
    angiography: 'CD proximal',
    teachingPoints: [
      'ST III > ST II y ST V1 ≥ 0 sugieren CD sobre CX.',
      'La bradicardia vagal es típica del IAM inferior.',
      'Pedir derivaciones derechas ante todo IAM inferior.',
      'Las náuseas y los vómitos son equivalentes anginosos frecuentes en el IAM inferior.',
    ],
    pitfalls: [
      'Atribuir los síntomas a un proceso gastrointestinal.',
      'Olvidar las derivaciones derechas en todo IAM inferior.',
    ],
    refs: [48, 54],
  },
  {
    id: 'A05',
    group: 'A',
    title: 'Inferior por CX',
    difficulty: 2,
    vignette: {
      age: 55,
      sex: 'M',
      history: 'Varón de 55 años con dolor torácico opresivo de 1 hora de evolución.',
      vitals: 'PA 135/85, FC 88',
      troponin: 'hs-cTnT 120 ng/L',
      symptomsOnsetMin: 60,
    },
    scenario: {
      seed: 105,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 88 },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-lcx', st: 0.2, refLead: 'II', shape: 'straight' },
        { territory: 'posterior', st: 0.1, refLead: 'V8', shape: 'straight' },
        { territory: 'lateral', st: 0.1, refLead: 'V6', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CX dominante',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: ['rv-involvement'],
    },
    angiography: 'CX dominante',
    teachingPoints: [
      'ST II ≥ III y aVL isoeléctrica orientan a CX frente a CD.',
      'El STE en V5–V6 con STD V1–V3 indica extensión posterolateral.',
      'Las derivaciones posteriores V7–V9 confirman la extensión.',
      'El infarto por CX puede ser electrocardiográficamente discreto frente al de CD.',
    ],
    pitfalls: [
      'Asumir que todo IAM inferior es de CD sin analizar los vectores.',
      'No registrar derivaciones posteriores ante STD precordial.',
    ],
    refs: [48, 49],
  },
  {
    id: 'A06',
    group: 'A',
    title: 'Tombstoning',
    difficulty: 2,
    vignette: {
      age: 49,
      sex: 'M',
      history:
        'Varón de 49 años con dolor torácico intenso de 30 minutos y shock. Sudoración profusa y palpitaciones.',
      vitals: 'PA 75/45, FC 120, SatO2 92 %',
      troponin: 'hs-cTnT pendiente',
      symptomsOnsetMin: 30,
    },
    scenario: {
      seed: 106,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 110 },
      conduction: 'normal',
      sources: [
        {
          territory: 'anteroseptal',
          st: 0.5,
          refLead: 'V2',
          shape: 'tombstone',
          terminalDistortion: 1,
        },
        { territory: 'anterior', st: 0.4, refLead: 'V3', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 30,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal',
      positiveFindings: ['stemi-udmi4', 'terminal-qrs-distortion'],
      negativeFindings: ['rv-involvement'],
    },
    angiography: 'DA proximal TIMI 0',
    teachingPoints: [
      'La distorsión terminal del QRS (J/R ≥ 0.5, pérdida de S) es marcador de oclusión proximal y alto riesgo.',
      'El tombstoning indica isquemia transmural grave.',
      'No confundir la amplitud del STE con benignidad: es un patrón de máximo riesgo.',
      'El tombstoning corresponde a lesiones proximales con gran masa de miocardio en riesgo.',
    ],
    pitfalls: [
      'Confundir el patrón con una taquicardia ventricular o un artefacto.',
      'Esperar al resultado de troponina para activar.',
    ],
    refs: [68, 25],
  },
  {
    id: 'A07',
    group: 'A',
    title: 'Lateral alto / D1 (bandera sudafricana)',
    difficulty: 3,
    vignette: {
      age: 60,
      sex: 'F',
      history:
        'Mujer de 60 años con dolor torácico de 50 minutos sin factores de riesgo destacables.',
      vitals: 'PA 150/90, FC 85',
      troponin: 'hs-cTnT 60 ng/L',
      symptomsOnsetMin: 50,
    },
    scenario: {
      seed: 107,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 85 },
      conduction: 'normal',
      sources: [{ territory: 'high-lateral', st: 0.14, refLead: 'aVL', shape: 'straight' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 50,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'D1',
      positiveFindings: ['south-african-flag'],
      negativeFindings: ['avr-diffuse-std'],
    },
    angiography: 'D1 TIMI 0',
    teachingPoints: [
      'El patrón I + aVL + V2 con STD III recuerda la bandera sudafricana.',
      'La oclusión de D1 puede cumplir criterios STEMI solo en I/aVL.',
      'Buscar siempre la recíproca inferior.',
      'La bandera sudafricana combina la derivación axial del primer diagonal con reciprocidad inferior.',
    ],
    pitfalls: [
      'Descartar la oclusión porque el STE parece escaso en las precordiales.',
      'No fijarse en la STD inferior como pista recíproca.',
    ],
    refs: [58, 5],
  },
  {
    id: 'A08',
    group: 'A',
    title: 'DA envolvente',
    difficulty: 2,
    vignette: {
      age: 62,
      sex: 'M',
      history:
        'Varón de 62 años con dolor torácico de 1 hora irradiado a mandíbula. Ansiedad marcada.',
      vitals: 'PA 125/75, FC 90',
      troponin: 'hs-cTnT 210 ng/L',
      symptomsOnsetMin: 60,
    },
    scenario: {
      seed: 108,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 90 },
      conduction: 'normal',
      sources: [
        { territory: 'anteroapical', st: 0.25, refLead: 'V4', shape: 'straight' },
        { territory: 'inferior-lcx', st: 0.12, refLead: 'II', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA distal envolvente',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: ['reciprocal-avl'],
    },
    angiography: 'DA distal envolvente',
    teachingPoints: [
      'STE anterior + inferior sin recíproca inferior sugiere DA envolvente (wraparound).',
      'La ausencia de STD inferior distingue la DA distal de la proximal.',
      'El vértice compartido explica el doble territorio.',
      'La DA envolvente (wraparound) produce lesión en los dos territorios compartidos del ápex.',
    ],
    pitfalls: [
      'Interpretar la suma de territorios como pericarditis difusa.',
      'No considerar la anatomía wraparound de la DA.',
    ],
    refs: [48, 5],
  },
  {
    id: 'A09',
    group: 'A',
    title: 'Posterior aislado con V7–V9',
    difficulty: 2,
    vignette: {
      age: 68,
      sex: 'F',
      history:
        'Mujer de 68 años con dolor epigástrico de 3 horas y náuseas. ECG inicial sin signos franco diagnosticables.',
      vitals: 'PA 140/85, FC 78',
      troponin: 'hs-cTnT 400 ng/L',
      symptomsOnsetMin: 180,
    },
    scenario: {
      seed: 109,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 78 },
      conduction: 'normal',
      sources: [{ territory: 'posterior', st: 0.2, refLead: 'V8', shape: 'straight' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 180,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CX/OM',
      positiveFindings: ['stemi-udmi4', 'posterior-std'],
      negativeFindings: ['de-winter'],
    },
    angiography: 'CX/OM',
    teachingPoints: [
      'El infarto posterior se manifiesta como STD V1–V3 con T alta (espejo).',
      'V7–V9 con STE ≥ 0.5 mm confirman la oclusión.',
      'Sin derivaciones posteriores este caso sería STEMI− en el 12 derivaciones.',
      'El dolor epigástrico es una presentación frecuente del infarto posterior/inferior.',
    ],
    pitfalls: [
      'No registrar las derivaciones posteriores ante la sospecha.',
      'Concluir normalidad tras un ECG de 12 derivaciones sin lesión evidente.',
    ],
    refs: [46, 5],
  },
  {
    id: 'A10',
    group: 'A',
    title: 'STEMI inferior post‑ROSC',
    difficulty: 2,
    vignette: {
      age: 52,
      sex: 'M',
      history:
        'Varón de 52 años con fibrilación ventricular al ingreso y RCP de 4 minutos con recuperación de circulación espontánea.',
      vitals: 'PA 100/60, FC 110',
      troponin: 'hs-cTnT pendiente',
    },
    scenario: {
      seed: 110,
      durationS: 5,
      rhythm: { type: 'pvc', hrBpm: 100, pvcPerMin: 6 },
      conduction: 'normal',
      sources: [{ territory: 'inferior-rca', st: 0.3, refLead: 'III', shape: 'straight' }],
      acquisition: { emg: { sigmaMv: 0.03 } },
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD media',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: [],
    },
    angiography: 'CD media',
    teachingPoints: [
      'La FV como primera manifestación de IAM inferior obliga a coronariografía urgente.',
      'Los PVCs frecuentes tras ROSC no invalidan la lectura del latido sinusal.',
      'El promediado del latido dominante limpia la interpretación.',
      'Tras ROSC con sospecha de causa coronaria la coronariografía urgente está indicada aunque el paciente esté estable.',
    ],
    pitfalls: [
      'Descartar isquemia por la frecuencia de ectopía post-ROSC.',
      'Demorar la angiografía esperando estabilización completa.',
    ],
    refs: [2, 12],
  },
];
