import type { CaseDefinition } from './types.js';

/** Group G — ritmos supraventriculares. docs/CASES.md §G. */
export const GROUP_G: CaseDefinition[] = [
  {
    id: 'G01',
    group: 'G',
    category: 'ritmo',
    title: 'Ritmo sinusal normal',
    difficulty: 1,
    vignette: {
      age: 30,
      sex: 'M',
      history:
        'Control preoperatorio en un paciente sano, sin antecedentes cardiovasculares ni medicación.',
      vitals: 'PA 118/74, FC 72',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 701,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['heart-rate', 'rr-irregular', 'wide-qrs', 'pr-prolonged', 'omi-composite'],
      diagnosis: 'Ritmo sinusal normal',
      distractors: [
        'Arritmia sinusal respiratoria',
        'Bloqueo AV de primer grado',
        'Bradicardia sinusal',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Cada QRS va precedido de una P positiva en II con PR estable y normal.',
      'La regularidad del RR es el punto de partida de toda lectura.',
      'Un ECG normal no excluye coronariopatía latente.',
      'Frecuencia 60–100, PR 120–200 ms, QRS < 120 ms definen la normalidad.',
    ],
    pitfalls: [
      'Sobrediagnosticar variantes normales de repolarización precoz.',
      'Omitir la medición sistemática de PR, QRS y QT.',
    ],
    refs: [126, 112],
  },
  {
    id: 'G02',
    group: 'G',
    category: 'ritmo',
    title: 'Bradicardia sinusal del atleta',
    difficulty: 1,
    vignette: {
      age: 24,
      sex: 'M',
      history:
        'Deportista de resistencia en revisión anual; asintomático, sin medicación, exploración normal.',
      vitals: 'PA 105/60, FC 44',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 702,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 44 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate'],
      negativeFindings: ['rr-irregular', 'av-dissociation', 'omi-composite'],
      diagnosis: 'Bradicardia sinusal',
      distractors: ['Bloqueo AV 2:1', 'Ritmo de la unión', 'Bloqueo AV completo'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'En el atleta entrenado, 40–50 lpm en reposo es una adaptación vagal frecuente.',
      'Clave: cada P conduce con PR normal y estable, sin pausas.',
      'La ausencia de síntomas orienta al tono vagal, no a enfermedad del nodo.',
      'Descartar causas: fármacos, hipotiroidismo, elevación de PIC.',
    ],
    pitfalls: [
      'Confundir P no conducidas ocultas con bradicardia sinusal pura.',
      'Pedir marcapasos ante una bradicardia fisiológica asintomática.',
    ],
    refs: [107, 125],
  },
  {
    id: 'G03',
    group: 'G',
    category: 'ritmo',
    title: 'Taquicardia sinusal por sepsis',
    difficulty: 1,
    vignette: {
      age: 68,
      sex: 'F',
      history:
        'Paciente con foco respiratorio, fiebre y deterioro general de 24 horas de evolución.',
      vitals: 'PA 98/60, FC 118, T 39.1 °C',
      troponin: 'hs-cTnT 45 ng/L',
    },
    scenario: {
      seed: 703,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 118 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate', 'u-wave'],
      negativeFindings: ['rr-irregular', 'wide-qrs', 'omi-composite'],
      diagnosis: 'Taquicardia sinusal',
      distractors: [
        'Flutter auricular 2:1',
        'Taquicardia supraventricular',
        'Fibrilación auricular rápida',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La taquicardia sinusal es un síntoma: buscar la causa (sepsis, dolor, anemia, TEV).',
      'P presente y normal antes de cada QRS descarta otras TSV.',
      'La frecuencia responde a la corrección del estímulo, no a antiarrítmicos.',
      'En sepsis, la troponina elevada puede reflejar daño miocárdico tipo 2.',
    ],
    pitfalls: [
      'Confundir taquicardia sinusal con flutter 2:1 por ondas F en la T.',
      'Tratar el número sin tratar la causa.',
    ],
    refs: [126, 112],
  },
  {
    id: 'G04',
    group: 'G',
    category: 'ritmo',
    title: 'Arritmia sinusal respiratoria',
    difficulty: 1,
    vignette: {
      age: 19,
      sex: 'F',
      history: 'Paciente joven asintomática; hallazgo incidental en un ECG previo a cirugía menor.',
      vitals: 'PA 110/70, FC 66',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 704,
      durationS: 10,
      rhythm: { type: 'sinus-arrhythmia', hrBpm: 66 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular'],
      negativeFindings: ['omi-composite', 'wide-qrs', 'av-dissociation'],
      diagnosis: 'Arritmia sinusal respiratoria',
      distractors: ['Fibrilación auricular', 'Extrasístoles auriculares', 'Bloqueo AV Mobitz I'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El RR se acorta con la inspiración y se alarga con la espiración.',
      'Las P son idénticas y cada una conduce: es fenómeno vagal fisiológico.',
      'Frecuente en jóvenes; desaparece con la apnea o el ejercicio.',
      'No requiere estudio ni tratamiento.',
    ],
    pitfalls: [
      'Confundirla con FA: aquí hay P en cada QRS y el patrón es cíclico.',
      'Etiquetarla como bloqueo o pausas patológicas.',
    ],
    refs: [126, 107],
  },
  {
    id: 'G05',
    group: 'G',
    category: 'ritmo',
    title: 'FA con respuesta ventricular rápida',
    difficulty: 2,
    vignette: {
      age: 76,
      sex: 'M',
      history:
        'Paciente hipertenso con palpitaciones y disnea de horas de evolución; no anticoagulado.',
      vitals: 'PA 142/88, FC 140',
      troponin: 'hs-cTnT 22 ng/L',
    },
    scenario: {
      seed: 705,
      durationS: 10,
      rhythm: { type: 'afib', hrBpm: 140 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate', 'rr-irregular', 'axis-deviation'],
      negativeFindings: ['pacing'],
      diagnosis: 'Fibrilación auricular con respuesta rápida',
      distractors: ['Flutter auricular variable', 'Taquicardia auricular multifocal', 'TSV'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'RR irregularmente irregular sin P discretas define la FA.',
      'La RVR se trata con control de frecuencia o cardioversión si inestable.',
      'Valorar CHA₂DS₂-VASc y duración antes de decidir anticoagulación.',
      'El flutter con bloqueo variable puede imitarla: buscar F regulares.',
    ],
    pitfalls: [
      'Llamar FA a un flutter con conducción variable.',
      'Reversiones de ST-T durante RVR leídas como isquemia.',
    ],
    refs: [113, 116],
  },
  {
    id: 'G06',
    group: 'G',
    category: 'ritmo',
    title: 'FA con respuesta lenta',
    difficulty: 2,
    vignette: {
      age: 81,
      sex: 'F',
      history:
        'Paciente con FA conocida en tratamiento con digoxina y betabloqueante; refiere debilidad.',
      vitals: 'PA 110/68, FC 46',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 706,
      durationS: 10,
      rhythm: { type: 'afib', hrBpm: 46 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [
        'heart-rate',
        'rr-irregular',
        'pr-prolonged',
        'av-dissociation',
        'flutter-waves',
      ],
      negativeFindings: ['omi-composite'],
      rulesMiss:
        'Las ondas f y la conducción irregular hacen que el detector lea actividad auricular organizada y un patrón tipo flutter.',
      diagnosis: 'Fibrilación auricular con respuesta lenta',
      distractors: ['Bloqueo AV completo', 'Bradicardia sinusal', 'Flutter con alto bloqueo'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'FA con respuesta < 50 sugiere exceso de nodal o disfunción intrínseca del nodo.',
      'Revisar dosis y niveles de digoxina, y la medicación betabloqueante.',
      'La irregularidad irregular diferencia FA de un escape juntoral regular.',
      'Una FA que se regulariza en bradicardia puede indicar BAV completo.',
    ],
    pitfalls: [
      'No sospechar intoxicación digitálica ante FA lenta.',
      'Confundir con ritmo de escape por bloqueo AV.',
    ],
    refs: [113, 128],
  },
  {
    id: 'G07',
    group: 'G',
    category: 'ritmo',
    title: 'Flutter auricular 2:1',
    difficulty: 2,
    vignette: {
      age: 58,
      sex: 'M',
      history: 'Paciente con palpitaciones de inicio súbito y taquicardia sostenida en urgencias.',
      vitals: 'PA 124/78, FC 150',
      troponin: 'hs-cTnT 15 ng/L',
    },
    scenario: {
      seed: 707,
      durationS: 10,
      rhythm: { type: 'flutter', atrialBpm: 300, ratio: 2 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate', 'flutter-waves', 'axis-deviation'],
      negativeFindings: ['rr-irregular'],
      diagnosis: 'Flutter auricular con conducción 2:1',
      distractors: ['Taquicardia sinusal', 'TSV por reentrada nodal', 'FA con respuesta rápida'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'TSV regular a ~150 lpm: pensar siempre en flutter 2:1.',
      'Las ondas F a 300/min quedan enterradas en el QRS/T en conducción par.',
      'Las maniobras vagales o el adenosino desenmascaran las ondas F.',
      'Inferior y V1 son las derivaciones donde mejor se ven las F.',
    ],
    pitfalls: [
      'Diagnosticar taquicardia sinusal y atrasar la cardioversión/ablación.',
      'Confundir la onda F con una T bifásica o una P.',
    ],
    refs: [116, 108],
  },
  {
    id: 'G08',
    group: 'G',
    category: 'ritmo',
    title: 'Flutter con conducción variable',
    difficulty: 2,
    vignette: {
      age: 64,
      sex: 'F',
      history:
        'Paciente con flutter conocido; la respuesta ventricular fluctúa durante la monitorización.',
      vitals: 'PA 128/80, FC 110',
      troponin: 'hs-cTnT 12 ng/L',
    },
    scenario: {
      seed: 708,
      durationS: 10,
      rhythm: { type: 'flutter', atrialBpm: 300, ratio: 3, variableRatio: true },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular', 'pr-prolonged', 'axis-deviation', 'flutter-waves'],
      negativeFindings: ['pacing'],
      diagnosis: 'Flutter auricular con conducción variable',
      distractors: ['Fibrilación auricular', 'Taquicardia auricular multifocal', 'TSV'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La conducción variable produce RR irregular con ondas F regulares.',
      'Diferencia clave con FA: la actividad auricular es organizada.',
      'Buscar F en II/III/aVF y V1 entre los QRS.',
      'El tratamiento sigue las mismas reglas de ritmo que el flutter fijo.',
    ],
    pitfalls: [
      'Llamar FA a un flutter variable y perder la opción de ablación del istmo.',
      'Ignorar las ondas F regulares tras el QRS.',
    ],
    refs: [116, 113],
  },
  {
    id: 'G09',
    group: 'G',
    category: 'ritmo',
    title: 'TSV (reentrada nodal)',
    difficulty: 2,
    vignette: {
      age: 35,
      sex: 'F',
      history:
        'Episodios recurrentes de palpitaciones de inicio y fin bruscos desde la adolescencia.',
      vitals: 'PA 118/72, FC 180',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 709,
      durationS: 10,
      rhythm: { type: 'svt', hrBpm: 180 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate', 'avr-diffuse-std', 'pathological-q'],
      negativeFindings: ['rr-irregular', 'wide-qrs', 'omi-composite'],
      diagnosis: 'Taquicardia supraventricular (TRNAV)',
      distractors: ['Flutter auricular 2:1', 'Taquicardia sinusal', 'Taquicardia ventricular'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'TSV regular de QRS estrecho a 150–250: el mecanismo más frecuente es TRNAV.',
      'La P retrógrada puede dibujar una pseudo-R′ en V1 o pseudo-S inferior.',
      'Responde a maniobras vagales y adenosina.',
      'El registro en crisis vale más que un ECG basal normal.',
    ],
    pitfalls: [
      'Descartar la P retrógrada y llamarla taquicardia sinusal.',
      'Olvidar el estudio de ablación tras episodios recurrentes.',
    ],
    refs: [108, 116],
  },
  {
    id: 'G10',
    group: 'G',
    category: 'ritmo',
    title: 'Ritmo de la unión',
    difficulty: 2,
    vignette: {
      age: 70,
      sex: 'M',
      history: 'Paciente bradicárdico con mareo; en tratamiento con diltiazem por hipertensión.',
      vitals: 'PA 108/66, FC 48',
      troponin: 'hs-cTnT 16 ng/L',
    },
    scenario: {
      seed: 710,
      durationS: 10,
      rhythm: { type: 'junctional', hrBpm: 48 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate'],
      negativeFindings: ['omi-composite', 'wide-qrs'],
      diagnosis: 'Ritmo de la unión',
      distractors: ['Bradicardia sinusal', 'Bloqueo AV completo', 'Ritmo idioventricular'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'QRS estrecho a 40–60 sin P precedente, o con P retrógrada, indica ritmo juntoral.',
      'Causas: fármacos nodales, isquemia inferior, aumento de tono vagal.',
      'La P retrógrada puede preceder, fusionarse o seguir al QRS.',
      'Revisar medicación y buscar síntomas de bajo gasto.',
    ],
    pitfalls: [
      'Confundirlo con bradicardia sinusal por no buscar la P ausente/retrógrada.',
      'Atribuirlo siempre a marcapasos: el escape juntoral es fisiológico protector.',
    ],
    refs: [107, 126],
  },
];
