import type { CaseDefinition } from './types.js';
import { lowVoltageOverrides } from '../engine/index.js';

/** Group N — estructural / otros. docs/CASES.md §N. */
export const GROUP_N: CaseDefinition[] = [
  {
    id: 'N01',
    group: 'N',
    category: 'estructural',
    title: 'Hipertrofia ventricular izquierda por voltaje',
    difficulty: 1,
    vignette: {
      age: 62,
      sex: 'M',
      history: 'Paciente con hipertensión de larga evolución; ECG de control ambulatorio.',
      vitals: 'PA 152/90, FC 70',
      troponin: 'hs-cTnT 22 ng/L',
    },
    scenario: {
      seed: 771,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'lvh',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['lvh-voltage'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Hipertrofia ventricular izquierda',
      distractors: ['Bloqueo completo de rama izquierda', 'Isquemia lateral', 'Normalidad'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Los criterios de Sokolow-Lyon y Cornell detectan HVI por voltaje.',
      'La HVI puede acompañarse de sobrecarga o “strain” secundario.',
      'Correlacionar con presión arterial y ecocardiograma.',
      'La HVI puede ocultar o imitar isquemia.',
    ],
    pitfalls: [
      'Diagnosticar isquemia solo por las alteraciones secundarias del ST-T.',
      'No medir el voltaje de forma sistemática.',
    ],
    refs: [111, 124],
  },
  {
    id: 'N02',
    group: 'N',
    category: 'estructural',
    title: 'Hipertrofia ventricular derecha',
    difficulty: 2,
    vignette: {
      age: 71,
      sex: 'F',
      history: 'Paciente con EPOC y disnea crónica; ECG con eje derecho y predominio derecho.',
      vitals: 'PA 124/78, FC 76',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 772,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 76 },
      conduction: 'rvh',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['axis-deviation'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Hipertrofia ventricular derecha',
      distractors: ['Hemibloqueo posterior', 'Dextrocardia', 'Infarto posterior'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La HVD produce eje derecho y R dominante en V1.',
      'La sobrecarga puede añadir T negativas en V1–V3.',
      'Debe diferenciarse del hemibloqueo posterior y la dextrocardia.',
      'La clínica y el ecocardiograma confirman el diagnóstico.',
    ],
    pitfalls: [
      'Confundir la HVD con un hemibloqueo posterior aislado.',
      'No sospecharla por falta de síntomas floridos.',
    ],
    refs: [111, 124],
  },
  {
    id: 'N03',
    group: 'N',
    category: 'estructural',
    title: 'Bajo voltaje con taquicardia',
    difficulty: 2,
    vignette: {
      age: 64,
      sex: 'M',
      history: 'Paciente con derrame pericárdico conocido y disnea; ECG de urgencias.',
      vitals: 'PA 98/62, FC 118',
      troponin: 'hs-cTnT 42 ng/L',
    },
    scenario: {
      seed: 773,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 118 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: { ...lowVoltageOverrides(), alternans: 0.3, aTScale: 0.45 },
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['low-voltage', 'heart-rate', 'pathological-q', 'u-wave'],
      negativeFindings: [],
      diagnosis: 'Derrame pericárdico con bajo voltaje',
      distractors: ['Hipotensión por sepsis', 'Infarto anterior', 'Neumotórax a tensión'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El bajo voltaje con taquicardia sugiere derrame pericárdico significativo.',
      'La alternancia eléctrica refuerza la sospecha cuando aparece.',
      'El diagnóstico es ecocardiográfico, no solo electrocardiográfico.',
      'La prioridad es estabilizar y valorar pericardiocentesis.',
    ],
    pitfalls: [
      'Llamar bajo voltaje a un registro con ganancia mal calibrada.',
      'No buscar alternancia eléctrica si el voltaje es bajo.',
    ],
    refs: [111, 124],
  },
  {
    id: 'N04',
    group: 'N',
    category: 'estructural',
    title: 'Dextrocardia',
    difficulty: 2,
    vignette: {
      age: 44,
      sex: 'M',
      history: 'Paciente con hallazgo de eje y precordiales atípicos en un chequeo.',
      vitals: 'PA 118/74, FC 72',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 774,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'normal',
      sources: [],
      variability: false,
      acquisition: { placement: 'dextrocardia' },
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['axis-deviation'],
      negativeFindings: ['av-dissociation', 'omi-composite'],
      diagnosis: 'Dextrocardia',
      distractors: ['Intercambio de electrodos de brazos', 'Hemibloqueo posterior', 'Normalidad'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La dextrocardia invierte el campo frontal y la progresión precordial.',
      'Sospecharla si I es negativa y aVR muestra actividad positiva.',
      'Repetir con electrodos en posición derecha para confirmar.',
      'Puede simular patología si no se reconoce.',
    ],
    pitfalls: [
      'Confundirla con una derivación mal colocada.',
      'No verificar la progresión precordial reversa.',
    ],
    refs: [126, 112],
  },
  {
    id: 'N05',
    group: 'N',
    category: 'estructural',
    title: 'Hipotermia con onda de Osborn',
    difficulty: 3,
    vignette: {
      age: 82,
      sex: 'F',
      history: 'Paciente encontrada con hipotermia tras exposición al frío; ECG en urgencias.',
      vitals: 'PA 96/60, FC 40',
      troponin: 'hs-cTnT 30 ng/L',
    },
    scenario: {
      seed: 775,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 40 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: { osbornMv: 0.18, qtc: 520 },
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate'],
      negativeFindings: [],
      diagnosis: 'Hipotermia con onda de Osborn',
      distractors: ['Isquemia por infarto', 'Bradicardia sinusal', 'Bloqueo AV completo'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La onda de Osborn es una deflexión positiva en la zona del J.',
      'La hipotermia suele acompañarse de bradicardia y temblor muscular.',
      'No confundirla con isquemia aguda.',
      'Corregir la temperatura resuelve el patrón.',
    ],
    pitfalls: [
      'Interpretar la onda de Osborn como lesión epicárdica.',
      'No medir la temperatura en un ECG con J prominent.',
    ],
    refs: [127, 112],
  },
  {
    id: 'N06',
    group: 'N',
    category: 'estructural',
    title: 'Brugada tipo 1',
    difficulty: 3,
    vignette: {
      age: 36,
      sex: 'M',
      history:
        'Paciente con síncope nocturno y antecedente familiar de muerte súbita; ECG de urgencias.',
      vitals: 'PA 122/78, FC 68',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 776,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 68 },
      conduction: 'normal',
      sources: [{ territory: 'rvot', st: 0.24, refLead: 'V1', shape: 'convex', tInversion: 0.8 }],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['stemi-udmi4', 'terminal-qrs-distortion'],
      negativeFindings: [],
      rulesMiss:
        'El STE en coved de V1–V3 cumple literalmente los umbrales de oclusión; el contexto y la forma distinguen el Brugada.',
      diagnosis: 'Patrón Brugada tipo 1',
      distractors: ['Bloqueo completo de rama derecha', 'Infarto anterior', 'Hipotermia'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El patrón Brugada 1 es STE cóncavo/coved en V1–V3 con T negativa.',
      'Es un patrón dinámico y no un síndrome aislado por sí solo.',
      'No equivale a infarto, aunque puede imitarlo.',
      'La historia de síncope y familia de muerte súbita lo hace relevante.',
    ],
    pitfalls: [
      'Llamar isquemia a un Brugada 1 típico.',
      'Descartar el síndrome si el patrón no está presente en un solo ECG.',
    ],
    refs: [119, 120],
  },
];
