import type { CaseDefinition } from './types.js';

/** Group B — oclusión sutil (STEMI− OMI). docs/CASES.md §B. */
export const GROUP_B: CaseDefinition[] = [
  {
    id: 'B01',
    group: 'B',
    title: 'T hiperagudas DA',
    difficulty: 3,
    vignette: {
      age: 47,
      sex: 'M',
      history:
        'Varón de 47 años con dolor torácico de 25 minutos. El ECG de triage fue leído como «normal».',
      vitals: 'PA 135/85, FC 88',
      troponin: 'hs-cTnT 18 ng/L',
      symptomsOnsetMin: 25,
    },
    scenario: {
      seed: 201,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 85 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.06, refLead: 'V3', shape: 'concave', hyperacuteT: 2.0 },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 12,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA media',
      positiveFindings: ['hyperacute-t'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'DA media TIMI 1',
    teachingPoints: [
      'La T hiperaguda precede al STE: área T/QRS aumentada y T simétrica.',
      'Un ECG «normal» a los 25 min de dolor no descarta OMI.',
      'Repetir el ECG en 10–15 min y comparar.',
    ],
    pitfalls: ['Las T hiperagudas se confunden con repolarización precoz o hiperpotasemia.'],
    refs: [26, 27],
  },
  {
    id: 'B02',
    group: 'B',
    title: 'De Winter',
    difficulty: 3,
    vignette: {
      age: 44,
      sex: 'M',
      history: 'Varón de 44 años, fumador, con dolor torácico de 45 minutos.',
      vitals: 'PA 130/80, FC 95',
      troponin: 'hs-cTnT 90 ng/L',
      symptomsOnsetMin: 45,
    },
    scenario: {
      seed: 202,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 95 },
      conduction: 'normal',
      sources: [
        {
          territory: 'anterior',
          st: -0.15,
          refLead: 'V3',
          shape: 'depression-upsloping',
          hyperacuteT: 1.6,
        },
        { territory: 'anteroseptal', st: 0.04, refLead: 'V1', shape: 'straight' },
      ],
    },
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal',
      positiveFindings: ['de-winter'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'DA proximal TIMI 0',
    teachingPoints: [
      'STD ascendente en J con T alta simétrica en V2–V6 equivale a oclusión de DA.',
      'El STE en aVR (0.5–1 mm) apoya el diagnóstico.',
      'No esperar troponina ni «STEMI»: es una emergencia de reperfusión.',
    ],
    refs: [36, 37],
  },
  {
    id: 'B03',
    group: 'B',
    title: 'STE sutil V2–V3: Smith 4v positivo',
    difficulty: 3,
    vignette: {
      age: 39,
      sex: 'M',
      history: 'Varón de 39 años con dolor torácico de 1 hora. STE sutil en V2–V3.',
      vitals: 'PA 125/80, FC 76',
      troponin: 'hs-cTnT 55 ng/L',
      symptomsOnsetMin: 60,
    },
    scenario: {
      seed: 203,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 76 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.12, refLead: 'V3', shape: 'straight', hyperacuteT: 0.8 },
      ],
      beatOverrides: { qtc: 420 },
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA media',
      positiveFindings: ['smith-4v'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'DA media',
    teachingPoints: [
      'Las fórmulas de Smith separan OMI anterior sutil de repolarización precoz.',
      'STE a J+60, QTc y amplitud R en V4 son las variables clave.',
      'Un QTc prolongado favorece OMI frente a RP.',
    ],
    refs: [66, 67],
  },
  {
    id: 'B04',
    group: 'B',
    title: 'Posterior sin V7–V9',
    difficulty: 2,
    vignette: {
      age: 72,
      sex: 'F',
      history:
        'Mujer de 72 años con dolor torácico de 2 horas. Solo se registraron 12 derivaciones estándar.',
      vitals: 'PA 145/90, FC 82',
      troponin: 'hs-cTnT 85 ng/L',
      symptomsOnsetMin: 120,
    },
    scenario: {
      seed: 204,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 82 },
      conduction: 'normal',
      sources: [{ territory: 'posterior', st: 0.14, refLead: 'V8', shape: 'straight' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 120,
    // Solo el ECG estándar de 12 derivaciones (sin V7–V9 ni V3R–V4R).
    leadsAvailable: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'],
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CX',
      positiveFindings: ['posterior-std'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'CX TIMI 0',
    teachingPoints: [
      'STD horizontal V1–V4 con T positiva = infarto posterior hasta demostración contraria.',
      'La regla posterior-std no exige V7–V9: el espejo en V1–V3 basta.',
      'Registrar V7–V9 ante cualquier STD V1–V3.',
    ],
    refs: [46, 47],
  },
  {
    id: 'B05',
    group: 'B',
    title: 'Aslanger',
    difficulty: 3,
    vignette: {
      age: 69,
      sex: 'M',
      history: 'Varón de 69 años, diabético, enfermedad de 3 vasos conocida, dolor de 1 hora.',
      vitals: 'PA 110/65, FC 98',
      troponin: 'hs-cTnT 150 ng/L',
      symptomsOnsetMin: 60,
    },
    scenario: {
      seed: 205,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 98 },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-rca', st: 0.2, refLead: 'III', shape: 'straight' },
        { territory: 'subendocardial', st: -0.22, refLead: 'V5', shape: 'straight' },
      ],
    },
    // ECG estándar de 12 derivaciones: el patrón de Aslanger se define sobre el 12.
    leadsAvailable: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'],
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD aguda + enfermedad 3 vasos',
      positiveFindings: ['aslanger', 'avr-diffuse-std', 'reciprocal-avl'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'CD aguda + enfermedad 3 vasos',
    teachingPoints: [
      'Aslanger: STE aislado en III, STD lateral V4–V6, ST V1 > V2.',
      'Indica OMI con enfermedad multivaso: prioriza la angiografía.',
      'La STD difusa subendocárdica se superpone a la lesión inferior.',
    ],
    refs: [45],
  },
  {
    id: 'B06',
    group: 'B',
    title: 'Inferior sutil con aVL recíproca',
    difficulty: 2,
    vignette: {
      age: 58,
      sex: 'F',
      history: 'Mujer de 58 años con dolor torácico de 40 minutos. STE inferior < 1 mm.',
      vitals: 'PA 130/80, FC 74',
      troponin: 'hs-cTnT 35 ng/L',
      symptomsOnsetMin: 40,
    },
    scenario: {
      seed: 206,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 74 },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-rca', st: 0.1, refLead: 'III', shape: 'concave', hyperacuteT: 3.0 },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 40,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD media',
      positiveFindings: ['reciprocal-avl', 'hyperacute-t'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'CD media',
    teachingPoints: [
      'La STD en aVL es la recíproca más sensible del IAM inferior.',
      'STE < 1 mm inferior + STD aVL = oclusión hasta demostración contraria.',
      'La T hiperaguda inferior acompaña la fase precoz.',
    ],
    refs: [70],
  },
  {
    id: 'B07',
    group: 'B',
    title: 'Lateral sutil / OM',
    difficulty: 3,
    vignette: {
      age: 61,
      sex: 'M',
      history:
        'Varón de 61 años con dolor torácico intermitente de 3 horas. STE sutil en I/aVL/V6.',
      vitals: 'PA 140/85, FC 80',
      troponin: 'hs-cTnT 210 ng/L',
      symptomsOnsetMin: 180,
    },
    scenario: {
      seed: 207,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 80 },
      conduction: 'normal',
      sources: [
        { territory: 'lateral', st: 0.07, refLead: 'V6', shape: 'straight' },
        { territory: 'posterior', st: 0.06, refLead: 'V8', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 180,
    leadsAvailable: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'],
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'OM1',
      positiveFindings: ['posterior-std'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'OM1 TIMI 1',
    teachingPoints: [
      'Las arterias marginales producen STE sutil o ausente.',
      'La troponina elevada y el dolor persistente mandan a angiografía.',
      'El componente posterior da la pista (STD V1–V3).',
    ],
    refs: [57],
  },
  {
    id: 'B08',
    group: 'B',
    title: 'LBBB + Sgarbossa modificado',
    difficulty: 3,
    vignette: {
      age: 76,
      sex: 'F',
      history: 'Mujer de 76 años con LBBB conocido y dolor torácico de 1 hora.',
      vitals: 'PA 135/80, FC 88',
      troponin: 'hs-cTnT 320 ng/L',
      symptomsOnsetMin: 60,
    },
    scenario: {
      seed: 208,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 88 },
      conduction: 'lbbb',
      sources: [{ territory: 'anteroseptal', st: 0.15, refLead: 'V2', shape: 'straight' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal',
      positiveFindings: ['sgarbossa-modified', 'barcelona'],
      negativeFindings: ['rv-involvement'],
    },
    angiography: 'DA proximal',
    teachingPoints: [
      'En LBBB el STE concordante ≥1 mm o discordante excesivo indica OMI.',
      'BARCELONA mejora la sensibilidad del Sgarbossa modificado.',
      'El LBBB conocido no retrasa la reperfusión si hay criterios.',
    ],
    refs: [62, 63],
  },
  {
    id: 'B09',
    group: 'B',
    title: 'Marcapasos + oclusión',
    difficulty: 3,
    vignette: {
      age: 80,
      sex: 'M',
      history: 'Varón de 80 años con marcapasos VVI y dolor torácico de 2 horas.',
      vitals: 'PA 120/70, FC 70 (marcapasos)',
      troponin: 'hs-cTnT 260 ng/L',
      symptomsOnsetMin: 120,
    },
    scenario: {
      seed: 209,
      durationS: 5,
      rhythm: { type: 'paced-rhythm', hrBpm: 70 },
      conduction: 'paced',
      sources: [{ territory: 'inferior-rca', st: 0.15, refLead: 'III', shape: 'straight' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 120,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD',
      positiveFindings: ['sgarbossa-modified'],
      negativeFindings: ['stemi-udmi4', 'rv-involvement'],
    },
    angiography: 'CD',
    teachingPoints: [
      'En ritmo estimulado se aplican los criterios de Sgarbossa.',
      'Buscar concordancia o discordancia excesiva del ST.',
      'La espiga de marcapasos no invalida el análisis del ST.',
    ],
    refs: [62, 64],
  },
  {
    id: 'B10',
    group: 'B',
    title: 'BRD + STE anteroseptal',
    difficulty: 2,
    vignette: {
      age: 66,
      sex: 'M',
      history: 'Varón de 66 años con dolor torácico de 1 hora e hipotensión. BRD en el ECG.',
      vitals: 'PA 90/55, FC 105',
      troponin: 'hs-cTnT 180 ng/L',
      symptomsOnsetMin: 60,
    },
    scenario: {
      seed: 210,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 105 },
      conduction: 'rbbb',
      sources: [{ territory: 'anteroseptal', st: 0.2, refLead: 'V2', shape: 'convex' }],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal pre-S1',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: ['rv-involvement'],
    },
    angiography: 'DA proximal pre-S1',
    teachingPoints: [
      'El BRD no oculta el STE: la discordancia solo afecta a V1–V2 terminales.',
      'BRD + IAM anterior = DA proximal pre-S1: máximo riesgo.',
      'No esperar a «estabilizar»: activar código infarto.',
    ],
    refs: [65],
  },
  {
    id: 'B11',
    group: 'B',
    title: 'Distorsión terminal con STE sutil',
    difficulty: 3,
    vignette: {
      age: 50,
      sex: 'M',
      history: 'Varón de 50 años con dolor torácico de 35 minutos. STE < 1 mm con J alto.',
      vitals: 'PA 130/85, FC 84',
      troponin: 'hs-cTnT 30 ng/L',
      symptomsOnsetMin: 35,
    },
    scenario: {
      seed: 211,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 84 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.1, refLead: 'V3', shape: 'convex', terminalDistortion: 0.9 },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 35,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA',
      positiveFindings: ['terminal-qrs-distortion'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'DA',
    teachingPoints: [
      'La pérdida de la S o J/R ≥ 0.5 en V2–V3 indica oclusión sin STE formal.',
      'La distorsión terminal se asocia a peor pronóstico.',
      'Mirar el J en relación con la R, no solo el STE absoluto.',
    ],
    refs: [68],
  },
  {
    id: 'B12',
    group: 'B',
    title: 'Wellens A tras dolor resuelto',
    difficulty: 3,
    vignette: {
      age: 54,
      sex: 'M',
      history: 'Varón de 54 años: dolor torácico de 30 minutos ayer noche; hoy asintomático.',
      vitals: 'PA 130/80, FC 70',
      troponin: 'hs-cTnT 45 ng/L',
      symptomsOnsetMin: 720,
    },
    scenario: {
      seed: 212,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.3, refLead: 'V3', shape: 'straight' }],
      timeline: [
        { atMin: 0, kind: 'occlusion' },
        { atMin: 40, kind: 'reperfusion' },
      ],
    },
    ecgAtMin: 720,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA prox 95 % TIMI 3',
      positiveFindings: ['wellens'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'DA proximal 95 % TIMI 3',
    teachingPoints: [
      'Wellens = T de reperfusión: el paciente está «bien» pero la lesión persiste.',
      'Patrón A: T bifásica terminal negativa en V2–V4.',
      'Contraindicada la prueba de esfuerzo; angiografía urgente.',
    ],
    refs: [38, 39],
  },
  {
    id: 'B13',
    group: 'B',
    title: 'Wellens B',
    difficulty: 3,
    vignette: {
      age: 59,
      sex: 'F',
      history: 'Mujer de 59 años sin dolor actual. Troponina elevada hallada en analítica.',
      vitals: 'PA 125/75, FC 72',
      troponin: 'hs-cTnT 120 ng/L',
    },
    scenario: {
      seed: 213,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.3, refLead: 'V3', shape: 'straight' }],
      timeline: [
        { atMin: 0, kind: 'occlusion' },
        { atMin: 60, kind: 'reperfusion' },
      ],
    },
    ecgAtMin: 2000,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal 90 %',
      positiveFindings: ['wellens'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'DA proximal 90 %',
    teachingPoints: [
      'Wellens B: T profundas simétricas en V2–V4 — lesión crítica reperfundida.',
      'La troponina positiva + Wellens = angiografía en 24 h máximo.',
      'Sin STE los criterios STEMI no se cumplen: reconocer el patrón.',
    ],
    refs: [38, 39],
  },
  {
    id: 'B14',
    group: 'B',
    title: 'Pseudonormalización (reoclusión)',
    difficulty: 3,
    vignette: {
      age: 57,
      sex: 'M',
      history:
        'Varón de 57 años con Wellens previo; el dolor torácico recurre. El ECG muestra T «normalizadas».',
      vitals: 'PA 135/85, FC 92',
      troponin: 'hs-cTnT 85 ng/L',
      symptomsOnsetMin: 8,
    },
    scenario: {
      seed: 214,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 92 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.3, refLead: 'V3', shape: 'straight' }],
      timeline: [
        { atMin: 0, kind: 'occlusion' },
        { atMin: 60, kind: 'reperfusion' },
        { atMin: 1500, kind: 'reocclusion' },
      ],
    },
    ecgAtMin: 1508,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA proximal',
      positiveFindings: [],
      negativeFindings: ['stemi-udmi4', 'wellens'],
      rulesMiss:
        'La pseudonormalización a los 8 min de reoclusión muestra T positivas y STE incipiente sin regla positiva; el contexto (Wellens previo + dolor) define la OMI.',
    },
    angiography: 'DA proximal TIMI 0',
    teachingPoints: [
      'La pseudonormalización: T invertidas que se vuelven positivas = reoclusión.',
      'Comparar con el ECG previo es diagnóstico.',
      'El dolor recurrente tras Wellens es una urgencia.',
    ],
    refs: [71, 72],
  },
];
