import type { CaseDefinition } from './types.js';

/** Group I — bloqueos AV. docs/CASES.md §I. */
export const GROUP_I: CaseDefinition[] = [
  {
    id: 'I01',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV de primer grado',
    difficulty: 1,
    vignette: {
      age: 74,
      sex: 'M',
      history: 'Paciente hipertenso con fibrosis del sistema de conducción; ECG de revisión anual.',
      vitals: 'PA 138/82, FC 70',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 721,
      durationS: 10,
      rhythm: { type: 'av-block-1', hrBpm: 70, prMs: 260 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pr-prolonged'],
      negativeFindings: ['omi-composite', 'av-dissociation'],
      diagnosis: 'Bloqueo AV de primer grado',
      distractors: ['Bloqueo AV 2:1', 'Normalidad', 'Síndrome de preexcitación'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'PR > 200 ms con conducción 1:1 es bloqueo de primer grado.',
      'No hay latidos caídos: cada P va seguida de QRS.',
      'Suele ser nodal; benigno si aislado.',
      'Un PR muy largo puede producir pseudo-pacemaker síndrome.',
    ],
    pitfalls: [
      'Confundirlo con enfermedad nodal avanzada si está aislado.',
      'No medir el PR de forma sistemática.',
    ],
    refs: [107, 125],
  },
  {
    id: 'I02',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV Mobitz I (Wenckebach)',
    difficulty: 2,
    vignette: {
      age: 69,
      sex: 'F',
      history: 'Paciente con mareos ocasionales; en el registro aparecen pausas periódicas.',
      vitals: 'PA 130/78, FC 62',
      troponin: 'hs-cTnT 15 ng/L',
    },
    scenario: {
      seed: 722,
      durationS: 10,
      rhythm: { type: 'av-block-2-mobitz1', hrBpm: 62, ratio: '4:3' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular', 'pr-prolonged'],
      negativeFindings: ['omi-composite', 'av-dissociation'],
      diagnosis: 'Bloqueo AV Mobitz I (Wenckebach)',
      distractors: ['Bloqueo AV Mobitz II', 'Arritmia sinusal', 'ESA bloqueadas'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El PR se alarga progresivamente hasta que una P no conduce.',
      'La pausa es menor que el doble del intervalo PP.',
      'El RR se acorta antes de la pausa por el menor incremento de PR.',
      'Generalmente nodal: benigno si asintomático.',
    ],
    pitfalls: [
      'No agrupar los latidos: los grupos regulares sugieren Wenckebach.',
      'Confundirlo con bloqueo 2:1 si falta un ciclo completo.',
    ],
    refs: [107, 125],
  },
  {
    id: 'I03',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV Mobitz II',
    difficulty: 3,
    vignette: {
      age: 78,
      sex: 'M',
      history: 'Paciente con síncope reciente; ECG con caídas súbitas de QRS sin cambios de PR.',
      vitals: 'PA 128/80, FC 58',
      troponin: 'hs-cTnT 20 ng/L',
    },
    scenario: {
      seed: 723,
      durationS: 10,
      rhythm: { type: 'av-block-2-mobitz2', hrBpm: 58, ratio: '3:2' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate', 'rr-irregular'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Bloqueo AV Mobitz II',
      distractors: ['Bloqueo AV Mobitz I', 'Bloqueo AV 2:1', 'Bradicardia sinusal'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El PR permanece constante hasta que un QRS cae de forma súbita.',
      'Generalmente infranodal: riesgo de progresión a BAV completo.',
      'La presencia de BRD o bloqueo fascicular asociado aumenta la sospecha.',
      'Indica evaluación urgente de estimulación si sintomático.',
    ],
    pitfalls: [
      'Confundirlo con Mobitz I por no comprobar la constancia del PR.',
      'No indicar marcapasos ante un bloqueo infranodal sintomático.',
    ],
    refs: [107, 125],
  },
  {
    id: 'I04',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV 2:1',
    difficulty: 3,
    vignette: {
      age: 75,
      sex: 'F',
      history: 'Paciente con fatiga crónica; ECG con P que se alternan conducidas y bloqueadas.',
      vitals: 'PA 122/74, FC 46',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 724,
      durationS: 10,
      rhythm: { type: 'av-block-2-mobitz2', hrBpm: 46, ratio: '2:1' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate', 'qtc-short'],
      negativeFindings: ['omi-composite', 'av-dissociation'],
      diagnosis: 'Bloqueo AV 2:1',
      distractors: ['Bradicardia sinusal', 'Bloqueo AV completo', 'Ritmo de la unión'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Dos P por cada QRS, con una conducida y otra bloqueada.',
      'No permite clasificar como Mobitz I ni II: necesita más conducción.',
      'El PR conducido suele ser constante, pero no diagnóstico.',
      'Descartar fármacos y causas reversibles antes de decidir.',
    ],
    pitfalls: [
      'Clasificarlo automáticamente como Mobitz II sin más evidencia.',
      'No descartar una P bloqueada oculta en la T.',
    ],
    refs: [107, 125],
  },
  {
    id: 'I05',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV de alto grado 3:1',
    difficulty: 3,
    vignette: {
      age: 80,
      sex: 'M',
      history: 'Paciente con síncope repetido y bradicardia marcada en el registro basal.',
      vitals: 'PA 110/64, FC 32',
      troponin: 'hs-cTnT 24 ng/L',
    },
    scenario: {
      seed: 725,
      durationS: 10,
      rhythm: { type: 'av-block-2-mobitz2', hrBpm: 32, ratio: '3:1' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular', 'axis-deviation'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Bloqueo AV de alto grado 3:1',
      distractors: ['Bradicardia sinusal', 'Bloqueo AV completo', 'Ritmo idioventricular'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Tres P por cada QRS indican bloqueo AV avanzado o de alto grado.',
      'Suele acompañarse de bradicardia sintomática.',
      'Buscar escapes ventriculares o juntorales asociados.',
      'Suele requerir estimulación si persiste.',
    ],
    pitfalls: [
      'Confundirlo con un ritmo de escape lento sin mirar las P.',
      'No reconocerlo como urgencia potencial.',
    ],
    refs: [107, 125],
  },
  {
    id: 'I06',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV completo con escape ventricular',
    difficulty: 3,
    vignette: {
      age: 82,
      sex: 'F',
      history:
        'Paciente con síncope reciente y disnea de bajo gasto; ingreso para valoración de marcapasos.',
      vitals: 'PA 104/60, FC 35',
      troponin: 'hs-cTnT 28 ng/L',
    },
    scenario: {
      seed: 726,
      durationS: 10,
      rhythm: { type: 'av-block-3', atrialBpm: 80, escapeBpm: 35, escapeOrigin: 'ventricular' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [
        'av-dissociation',
        'heart-rate',
        'stemi-udmi4',
        'reciprocal-avl',
        'terminal-qrs-distortion',
        'pathological-q',
        'pr-prolonged',
        'axis-deviation',
        'lvh-voltage',
      ],
      negativeFindings: ['pacing', 'flutter-waves'],
      rulesMiss:
        'El escape ventricular ancho genera discordancia ST/T secundaria que satisface las reglas de oclusión; la lesión real es el bloqueo completo.',
      diagnosis: 'Bloqueo AV completo con escape ventricular',
      distractors: ['Bradicardia sinusal', 'Ritmo idioventricular', 'Bloqueo AV 2:1'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Las P y los QRS se mueven independientes: disociación AV.',
      'El escape ventricular es ancho, lento y regular.',
      'La frecuencia auricular suele ser mayor que la ventricular.',
      'Requiere marcapasos definitivo si no hay causa reversible.',
    ],
    pitfalls: [
      'Confundir la disociación con isorritmia por taquicardia sinusal.',
      'No diferenciar el escape ventricular del juntorral.',
    ],
    refs: [107, 125],
  },
  {
    id: 'I07',
    group: 'I',
    category: 'bloqueo-av',
    title: 'Bloqueo AV completo con escape de la unión',
    difficulty: 3,
    vignette: {
      age: 77,
      sex: 'M',
      history: 'Paciente con debilidad y bradicardia estable en planta; ECG de control nocturno.',
      vitals: 'PA 116/70, FC 45',
      troponin: 'hs-cTnT 14 ng/L',
    },
    scenario: {
      seed: 770,
      durationS: 10,
      rhythm: { type: 'av-block-3', atrialBpm: 75, escapeBpm: 45, escapeOrigin: 'junctional' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['av-dissociation', 'heart-rate', 'pr-prolonged'],
      negativeFindings: ['omi-composite', 'wide-qrs'],
      diagnosis: 'Bloqueo AV completo con escape de la unión',
      distractors: ['Bradicardia sinusal', 'Ritmo de la unión', 'Bloqueo AV 2:1'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La disociación AV persiste aunque el escape sea estrecho.',
      'El escape juntoral suele mantener una frecuencia algo mayor.',
      'El PR es variable y no refleja conducción.',
      'La estabilidad hemodinámica no excluye la necesidad de marcapasos.',
    ],
    pitfalls: [
      'Descartar el bloqueo completo solo porque el QRS sea estrecho.',
      'Confundir las ondas P con artefactos o extrasístoles.',
    ],
    refs: [107, 125],
  },
];
