import type { CaseDefinition } from './types.js';

/** Group E — dinámica temporal. docs/CASES.md §E. */
export const GROUP_E: CaseDefinition[] = [
  {
    id: 'E01',
    group: 'E',
    title: 'Serie DA: evolución de la oclusión',
    difficulty: 3,
    vignette: {
      age: 60,
      sex: 'M',
      history: 'Serie temporal de oclusión de DA: T hiperaguda precede al STEMI franco.',
      vitals: 'PA 135/85, FC 90',
      troponin: 'hs-cTnT en ascenso',
    },
    scenario: {
      seed: 501,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 90 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.3, refLead: 'V3', shape: 'straight', hyperacuteT: 1.5 },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 10,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA',
      positiveFindings: ['hyperacute-t'],
      negativeFindings: ['stemi-udmi4'],
      rulesMiss: 'A 10 min la T hiperaguda ya es marcador OMI; STEMI llega ~40 min.',
    },
    angiography: 'DA TIMI 0',
    teachingPoints: [
      'La evolución natural: T hiperaguda → STE → Q → inversión de T.',
      'A 10 min hyperacute-t ya es positivo; stemi-udmi4 tarda.',
      'La serie temporal enseña el valor del ECG seriado.',
    ],
    refs: [22, 23],
  },
  {
    id: 'E02',
    group: 'E',
    title: 'Reperfusión exitosa',
    difficulty: 3,
    vignette: {
      age: 64,
      sex: 'F',
      history: 'IAM inferior reperfundido a los 50 min; ECG a 140 min con AIVR previa.',
      vitals: 'PA 120/75, FC 85',
      troponin: 'hs-cTnT 900 ng/L',
    },
    scenario: {
      seed: 502,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 85 },
      conduction: 'normal',
      sources: [{ territory: 'inferior-rca', st: 0.3, refLead: 'III', shape: 'straight' }],
      timeline: [
        { atMin: 0, kind: 'occlusion' },
        { atMin: 50, kind: 'reperfusion' },
      ],
    },
    ecgAtMin: 140,
    expected: {
      omi: true,
      activateCathLab: false,
      culprit: 'CD reperfundida',
      positiveFindings: [],
      negativeFindings: ['stemi-udmi4'],
      rulesMiss:
        'Tras reperfusión el STE cae <50 %; las reglas quedan negativas aunque hubo oclusión — la historia y la resolución del STE documentan la reperfusión.',
    },
    angiography: 'CD TIMI 3 tras PCI',
    teachingPoints: [
      'Resolución ≥50 % del STE a 60–90 min = criterio de reperfusión.',
      'La AIVR en la ventana post-reperfusión es marcador benigno.',
      'La T de reperfusión (inversión) aparece después.',
    ],
    refs: [71, 74],
  },
  {
    id: 'E03',
    group: 'E',
    title: 'Reoclusión',
    difficulty: 3,
    vignette: {
      age: 58,
      sex: 'M',
      history: 'IAM anterior reperfundido a los 60 min que se reocluye a las 4 h.',
      vitals: 'PA 125/80, FC 95',
      troponin: 'hs-cTnT 500 ng/L',
    },
    scenario: {
      seed: 503,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 95 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.3, refLead: 'V3', shape: 'straight', hyperacuteT: 1 },
      ],
      timeline: [
        { atMin: 0, kind: 'occlusion' },
        { atMin: 60, kind: 'reperfusion' },
        { atMin: 240, kind: 'reocclusion' },
      ],
    },
    ecgAtMin: 280,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA reocluida',
      positiveFindings: ['stemi-udmi4'],
      negativeFindings: [],
    },
    angiography: 'DA TIMI 0 (stent trombosado)',
    teachingPoints: [
      'La reoclusión borra la inversión de T (pseudonormalización) y vuelve el STE.',
      'Dolor recurrente post-PCI obliga a ECG seriado.',
      'La trombosis de stent es la causa clásica de reoclusión.',
    ],
    refs: [71, 72],
  },
  {
    id: 'E04',
    group: 'E',
    title: 'Multivaso Aslanger dinámico',
    difficulty: 3,
    vignette: {
      age: 70,
      sex: 'M',
      history: 'Paciente diabético: STD difusa a la que se superpone STE en III.',
      vitals: 'PA 105/60, FC 100',
      troponin: 'hs-cTnT 180 ng/L',
    },
    scenario: {
      seed: 504,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 100 },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-rca', st: 0.12, refLead: 'III', shape: 'straight' },
        { territory: 'subendocardial', st: -0.1, refLead: 'V5', shape: 'straight' },
      ],
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 60,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD + multivaso',
      positiveFindings: ['aslanger'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'CD aguda + enfermedad 3 vasos',
    teachingPoints: [
      'Enfermedad multivaso: la lesión focal se superpone a isquemia subendocárdica.',
      'STE aislado en III sobre STD difusa = patrón Aslanger.',
      'Prioriza angiografía aunque no haya STEMI clásico.',
    ],
    refs: [45],
  },
];
