import type { CaseDefinition } from './types.js';

/** Group F — adquisición y artefactos. docs/CASES.md §F. */
export const GROUP_F: CaseDefinition[] = [
  {
    id: 'F01',
    group: 'F',
    title: 'Filtro monitor 0.5 Hz',
    difficulty: 1,
    vignette: {
      age: 66,
      sex: 'F',
      history:
        'Paciente con dolor torácico monitorizado en una unidad con filtrado de línea base activado.',
      vitals: 'PA 130/80, FC 96',
      troponin: 'hs-cTnT 320 ng/L',
    },
    scenario: {
      seed: 601,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 96 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.25, refLead: 'V3', shape: 'straight' }],
      acquisition: { highPassHz: 0.5, highPassMode: 'causal' },
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 120,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA media',
      positiveFindings: [],
      negativeFindings: [],
    },
    angiography: 'DA media TIMI 0',
    teachingPoints: [
      'El filtro HP 0.5 Hz unidireccional distorsiona el segmento ST.',
      'Para diagnóstico usar 0.05 Hz (o fase cero).',
      'Comparar lado a lado revela el artefacto.',
      'El filtro de 0.5 Hz distorsiona el segmento ST y puede crear pseudo-depresión.',
    ],
    pitfalls: [
      'Diagnosticar STD causada por el filtro como isquemia.',
      'No cambiar a filtro diagnóstico (0.05 Hz) para el registro.',
    ],
    refs: [33, 99],
  },
  {
    id: 'F02',
    group: 'F',
    title: 'Ruido EMG y wander',
    difficulty: 1,
    vignette: {
      age: 47,
      sex: 'M',
      history:
        'Paciente agitado y diaforético durante el registro; el trazado resulta difícil de interpretar.',
      vitals: 'PA 135/85, FC 88',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 602,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 85 },
      variability: false,
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.06, refLead: 'V3', shape: 'concave', hyperacuteT: 0.45 },
        { territory: 'anteroseptal', st: 0.02, refLead: 'V2', shape: 'concave', hyperacuteT: 1.2 },
      ],
      acquisition: { emg: { sigmaMv: 0.06 }, baselineWander: { amplitudeMv: 0.3, hz: 0.3 } },
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 12,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'DA media',
      positiveFindings: [],
      negativeFindings: [],
    },
    angiography: 'DA media TIMI 1',
    teachingPoints: [
      'El ruido muscular y la respiración pueden ocultar T hiperagudas.',
      'El promediado del latido y «quitar ruido» recuperan la morfología.',
      'Ante la duda, repetir el ECG con el paciente tranquilo.',
      'El ruido muscular y la respiración pueden ocultar morfologías sutiles del ST-T.',
    ],
    pitfalls: [
      'Leer el trazado ruidoso sin repetir con el paciente en reposo.',
      'Ignorar el canal limpio cuando está disponible.',
    ],
    refs: [99, 106],
  },
  {
    id: 'F03',
    group: 'F',
    title: 'V1–V2 altos',
    difficulty: 1,
    vignette: {
      age: 34,
      sex: 'M',
      history:
        'Registro de un paciente sano realizado con los electrodos precordiales anteriores un espacio intercostal por encima de lo habitual.',
      vitals: 'PA 120/75, FC 68',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 603,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 68 },
      conduction: 'normal',
      sources: [],
      acquisition: { placement: 'v1v2-high' },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'wellens'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'V1–V2 altos producen rSr′ y T negativa: mimic de Brugada o IAM septal.',
      'Verificar la posición de los electrodos ante V1–V2 anómalos.',
      'Repetir con colocación estándar resuelve la duda.',
      'La colocación alta de electrodos precordiales produce patrones que imitan patología septal.',
    ],
    pitfalls: [
      'Diagnosticar patología sin verificar la posición de electrodos.',
      'No repetir el registro con la colocación correcta.',
    ],
    refs: [99, 106],
  },
  {
    id: 'F04',
    group: 'F',
    title: 'Powerline 60 Hz + LP 40 Hz',
    difficulty: 1,
    vignette: {
      age: 71,
      sex: 'M',
      history:
        'Paciente con dolor torácico; el registro muestra una interferencia rítmica uniforme durante toda la adquisición.',
      vitals: 'PA 90/55, FC 40',
      troponin: 'hs-cTnT 180 ng/L',
    },
    scenario: {
      seed: 604,
      durationS: 5,
      rhythm: { type: 'av-block-3', atrialBpm: 80, escapeBpm: 40 },
      conduction: 'normal',
      sources: [
        { territory: 'inferior-rca', st: 0.3, refLead: 'III', shape: 'straight' },
        { territory: 'rv', st: 0.15, refLead: 'V4R', shape: 'straight' },
      ],
      acquisition: { powerline: { hz: 60, amplitudeMv: 0.08 }, lowPassHz: 40 },
      timeline: [{ atMin: 0, kind: 'occlusion' }],
    },
    ecgAtMin: 90,
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'CD proximal',
      positiveFindings: [],
      negativeFindings: [],
    },
    angiography: 'CD proximal TIMI 0',
    teachingPoints: [
      'La interferencia de red añade un zumbido uniforme de 50/60 Hz.',
      'El LP 40 Hz limpia el ruido pero suaviza las espigas del QRS.',
      'Comparar clean vs filtrada enseña el efecto de cada filtro.',
      'La interferencia de red de 50/60 Hz es un artefacto reconocible y evitable.',
    ],
    pitfalls: [
      'Confundir la interferencia con arritmia o morfología anómala.',
      'No valorar el efecto del filtro LP sobre la amplitud real del QRS.',
    ],
    refs: [33, 99],
  },
];
