import type { CaseDefinition } from './types.js';
import {
  digoxinOverrides,
  hypocalcemiaOverrides,
  hypokalemiaOverrides,
  severeHyperkalemiaOverrides,
  longQtOverrides,
  shortQtOverrides,
} from '../engine/index.js';

/** Group M — electrolitos, fármacos y QT. docs/CASES.md §M. */
export const GROUP_M: CaseDefinition[] = [
  {
    id: 'M01',
    group: 'M',
    category: 'electrolitos',
    title: 'Hiperpotasemia moderada',
    difficulty: 2,
    vignette: {
      age: 66,
      sex: 'F',
      history:
        'Paciente con insuficiencia renal crónica y debilidad; ECG por sospecha de hiperpotasemia.',
      vitals: 'PA 118/72, FC 72',
      troponin: 'hs-cTnT 35 ng/L',
    },
    scenario: {
      seed: 761,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: { aTScale: 1.7, tSigmaScale: 0.6 },
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['peaked-t'],
      negativeFindings: ['omi-composite', 'u-wave'],
      diagnosis: 'Hiperpotasemia moderada',
      distractors: ['Síndrome coronario agudo', 'Hipotermia con onda J', 'QT largo congénito'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La hiperpotasemia moderada produce T picudas, simétricas y de base estrecha.',
      'El inicio suele ser precordial antes de ensanchar el QRS.',
      'Correlacionar con potasio sérico y función renal.',
      'La monitorización es útil mientras se corrige el K.',
    ],
    pitfalls: [
      'Llamar isquemia a unas T picudas por K alto.',
      'No medir el K si la T parece solo “alta”.',
    ],
    refs: [117, 112],
  },
  {
    id: 'M02',
    group: 'M',
    category: 'electrolitos',
    title: 'Hiperpotasemia severa',
    difficulty: 3,
    vignette: {
      age: 72,
      sex: 'M',
      history: 'Paciente con EPOC, insuficiencia renal y bradicardia marcada; ECG de urgencias.',
      vitals: 'PA 96/58, FC 50',
      troponin: 'hs-cTnT 60 ng/L',
    },
    scenario: {
      seed: 762,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 48 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: severeHyperkalemiaOverrides(),
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['peaked-t', 'heart-rate'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Hiperpotasemia severa',
      distractors: [
        'Bloqueo AV completo',
        'Bloqueo completo de rama izquierda',
        'Síndrome coronario agudo',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La hiperpotasemia severa ensancha el QRS y aplana la P.',
      'La bradicardia acompaña cuando el nodo sinusal se deprime.',
      'El diagnóstico es electrocardiográfico y bioquímico a la vez.',
      'Ante bradicardia y QRS muy ancho, tratar sin demora.',
    ],
    pitfalls: [
      'Confundir el QRS ancho con un bloqueo primario.',
      'No sospechar hiperpotasemia por la ausencia de historia clara.',
    ],
    refs: [117, 118],
  },
  {
    id: 'M03',
    group: 'M',
    category: 'electrolitos',
    title: 'Hipopotasemia',
    difficulty: 2,
    vignette: {
      age: 55,
      sex: 'F',
      history: 'Paciente con diuréticos y debilidad muscular; ECG por sospecha de hipopotasemia.',
      vitals: 'PA 128/80, FC 78',
      troponin: 'hs-cTnT 12 ng/L',
    },
    scenario: {
      seed: 763,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 78 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: hypokalemiaOverrides(),
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['u-wave'],
      negativeFindings: ['omi-composite', 'peaked-t'],
      diagnosis: 'Hipopotasemia',
      distractors: ['Hipotermia con onda J', 'QT largo', 'Isquemia subendocárdica'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La hipopotasemia aplanas la T y produce onda U prominente.',
      'La U suele verse mejor en V2–V3 tras la T.',
      'Correlacionar con diuréticos, pérdidas digestivas y magnesio.',
      'La corrección del K reduce el riesgo arrítmico.',
    ],
    pitfalls: ['Confundir la U con una P o una T bifásica.', 'No revisar el magnesio asociado.'],
    refs: [117, 112],
  },
  {
    id: 'M04',
    group: 'M',
    category: 'electrolitos',
    title: 'Hipocalcemia',
    difficulty: 2,
    vignette: {
      age: 49,
      sex: 'F',
      history:
        'Paciente con parestesias y tetania tras cirugía tiroidea; ECG por sospecha de hipocalcemia.',
      vitals: 'PA 118/74, FC 70',
      troponin: 'hs-cTnT 10 ng/L',
    },
    scenario: {
      seed: 764,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: hypocalcemiaOverrides(),
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['qtc-prolonged'],
      negativeFindings: [],
      diagnosis: 'Hipocalcemia',
      distractors: ['QT largo congénito', 'Hiperpotasemia', 'Isquemia subendocárdica'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La hipocalcemia alarga el QT por prolongación del ST.',
      'La T suele ser normal; el segmento isoeléctrico es el que se estira.',
      'Buscar tetania, parestesias y causas postquirúrgicas.',
      'Corregir Ca y Mg mejora el intervalo QT.',
    ],
    pitfalls: [
      'Llamar QT largo congénito a una hipocalcemia aguda.',
      'No revisar el magnesio asociado.',
    ],
    refs: [118, 112],
  },
  {
    id: 'M05',
    group: 'M',
    category: 'electrolitos',
    title: 'Hipercalcemia',
    difficulty: 2,
    vignette: {
      age: 74,
      sex: 'M',
      history:
        'Paciente con hiperparatiroidismo y confusión leve; ECG por sospecha de hipercalcemia.',
      vitals: 'PA 132/82, FC 68',
      troponin: 'hs-cTnT 16 ng/L',
    },
    scenario: {
      seed: 765,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 68 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: { stSegmentMs: -40, qtc: 340 },
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['qtc-short'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Hipercalcemia',
      distractors: ['QT corto congénito', 'Hipopotasemia', 'Normalidad'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La hipercalcemia acorta el ST y por tanto el QT.',
      'El QT corto aquí es adquirido, no congénito.',
      'Buscar síntomas neuro, GI y nefrológicos de Ca elevado.',
      'La corrección del Ca restaura la repolarización.',
    ],
    pitfalls: [
      'Diagnosticar QT corto congénito sin descartar Ca elevado.',
      'No correlacionar el ECG con la calcemia.',
    ],
    refs: [118, 112],
  },
  {
    id: 'M06',
    group: 'M',
    category: 'electrolitos',
    title: 'Efecto digitálico',
    difficulty: 2,
    vignette: {
      age: 78,
      sex: 'F',
      history: 'Paciente con FA en digoxina; ECG por control de tratamiento.',
      vitals: 'PA 116/70, FC 62',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 766,
      durationS: 10,
      rhythm: { type: 'afib', hrBpm: 62 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: digoxinOverrides(),
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Efecto digitálico',
      distractors: ['Isquemia subendocárdica', 'Hipopotasemia', 'Bloqueo AV completo'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La digital produce un ST en “cubeta” o sagging en derivaciones laterales.',
      'No significa toxicidad por sí solo, pero orienta a la medicación.',
      'El QT suele acortarse y la T puede achatarse.',
      'Correlacionar con niveles séricos y función renal.',
    ],
    pitfalls: [
      'Confundir el ST en cubeta con isquemia.',
      'No medir niveles de digoxina si hay bradicardia marcada.',
    ],
    refs: [128, 112],
  },
  {
    id: 'M07',
    group: 'M',
    category: 'electrolitos',
    title: 'Síndrome de QT largo congénito',
    difficulty: 2,
    vignette: {
      age: 21,
      sex: 'F',
      history: 'Paciente joven con síncope al ejercicio; ECG con QT llamativamente prolongado.',
      vitals: 'PA 112/70, FC 70',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 767,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: longQtOverrides(),
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['qtc-prolonged'],
      negativeFindings: [],
      diagnosis: 'Síndrome de QT largo',
      distractors: ['Hipocalcemia', 'Hiperpotasemia', 'Isquemia'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El QT largo congénito aumenta el riesgo de torsades y muerte súbita.',
      'El QTc se interpreta mejor con Fridericia o nomogramas.',
      'Buscar antecedentes familiares, síncope y triggers adrenérgicos.',
      'No confundir con causas adquiridas de QT largo.',
    ],
    pitfalls: [
      'Llamar QT largo congénito a una hipocalcemia aguda.',
      'No preguntar por síncope familiar o muerte súbita joven.',
    ],
    refs: [119, 121],
  },
  {
    id: 'M08',
    group: 'M',
    category: 'electrolitos',
    title: 'QT corto',
    difficulty: 2,
    vignette: {
      age: 27,
      sex: 'M',
      history: 'Paciente joven con antecedente familiar de muerte súbita; ECG de cribado.',
      vitals: 'PA 120/76, FC 74',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 768,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 74 },
      conduction: 'normal',
      sources: [],
      variability: false,
      beatOverrides: shortQtOverrides(),
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['qtc-short'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Síndrome de QT corto',
      distractors: ['Hipercalcemia', 'Normalidad', 'Digoxin effect'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El QT corto es una entidad rara asociada a arritmias malignas.',
      'La sospecha aumenta si el QTc es muy bajo y persistente.',
      'Revisar historia familiar y descartar causas adquiridas.',
      'Puede precisar estudio genético o seguimiento especializado.',
    ],
    pitfalls: [
      'Confundirlo con hipercalcemia sin medir calcio.',
      'Descartarlo por ser una entidad poco frecuente.',
    ],
    refs: [119, 121],
  },
];
