import type { CaseDefinition } from './types.js';

/** Group K — ritmos ventriculares y paro. docs/CASES.md §K. */
export const GROUP_K: CaseDefinition[] = [
  {
    id: 'K01',
    group: 'K',
    category: 'ventricular',
    title: 'Ritmo idioventricular acelerado',
    difficulty: 2,
    vignette: {
      age: 58,
      sex: 'M',
      history:
        'Paciente en monitorización tras infarto previo; aparece un ritmo lento y regular sin síntomas agudos.',
      vitals: 'PA 124/76, FC 72',
      troponin: 'hs-cTnT 30 ng/L',
    },
    scenario: {
      seed: 741,
      durationS: 10,
      rhythm: { type: 'idioventricular', hrBpm: 72 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [
        'stemi-udmi4',
        'rv-involvement',
        'reciprocal-avl',
        'terminal-qrs-distortion',
        'lvh-voltage',
      ],
      negativeFindings: ['pacing'],
      rulesMiss:
        'El QRS ancho ventricular con discordancia ST/T satisface las reglas de oclusión; el origen es un ritmo de escape acelerado.',
      diagnosis: 'Ritmo idioventricular acelerado',
      distractors: ['Ritmo de la unión', 'Bloqueo AV completo', 'TV lenta'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'RIVA: ritmo ventricular regular de 50–110 lpm, QRS ancho, sin relación AV.',
      'Suele verse tras reperfusión o en contexto de bajo gasto.',
      'Es autolimitado si la frecuencia es baja y el paciente está estable.',
      'Diferenciarlo de una TV lenta si es sostenido o sintomático.',
    ],
    pitfalls: [
      'Tratarlo como TV si el paciente está hemodinámicamente estable.',
      'No reconocer que la frecuencia baja lo diferencia de una TV.',
    ],
    refs: [109, 122],
  },
  {
    id: 'K02',
    group: 'K',
    category: 'ventricular',
    title: 'Taquicardia ventricular monomórfica',
    difficulty: 3,
    vignette: {
      age: 65,
      sex: 'M',
      history:
        'Paciente con infarto antiguo y disnea súbita; ECG de urgencias con QRS ancho regular.',
      vitals: 'PA 94/58, FC 170',
      troponin: 'hs-cTnT 85 ng/L',
    },
    scenario: {
      seed: 742,
      durationS: 10,
      rhythm: { type: 'vt', hrBpm: 170, atrialBpm: 75 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Taquicardia ventricular monomórfica',
      distractors: ['TSV con aberrancia', 'Flutter 2:1', 'Taquicardia sinusal'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'QRS ancho regular con frecuencia rápida orienta a TV.',
      'Brugada/Vereckei refuerzan el diagnóstico si hay disociación AV.',
      'Buscar fusiones y capturas si el ritmo no está estabilizado.',
      'En inestabilidad, cardioversión urgente.',
    ],
    pitfalls: [
      'Descartar TV porque el paciente tolera la frecuencia.',
      'No diferenciar TSV con aberrancia si no se analizan las P.',
    ],
    refs: [109, 114, 122],
  },
  {
    id: 'K03',
    group: 'K',
    category: 'ventricular',
    title: 'Torsades de pointes sobre QT largo',
    difficulty: 3,
    vignette: {
      age: 71,
      sex: 'F',
      history:
        'Paciente con hipopotasemia y QT prolongado tras antiarrítmico; palpitaciones y síncope.',
      vitals: 'PA 108/66, FC 190',
      troponin: 'hs-cTnT 40 ng/L',
    },
    scenario: {
      seed: 743,
      durationS: 10,
      rhythm: { type: 'torsades', hrBpm: 190 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['heart-rate'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Torsades de pointes',
      distractors: [
        'Taquicardia ventricular monomórfica',
        'Fibrilación ventricular',
        'TSV irregular',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La torsades es TV polimorfa sobre QT largo; el eje gira alrededor de la línea base.',
      'El magnesio intravenoso es el tratamiento inicial.',
      'Buscar causa del QT largo: fármacos, K, Ca, genética.',
      'No usar antiarrítmicos que prolonguen aún más el QT.',
    ],
    pitfalls: [
      'Llamarla TV monomorfa y no revisar el QT previo.',
      'Olvidar el magnesio como primera medida.',
    ],
    refs: [109, 122, 123],
  },
  {
    id: 'K04',
    group: 'K',
    category: 'ventricular',
    title: 'Fibrilación ventricular gruesa',
    difficulty: 3,
    vignette: {
      age: 69,
      sex: 'M',
      history: 'Paciente con paro súbito durante la monitorización; inicio de RCP y DEA.',
      vitals: 'PA —, FC —',
      troponin: 'hs-cTnT 120 ng/L',
    },
    scenario: {
      seed: 744,
      durationS: 10,
      rhythm: { type: 'vf', coarse: true },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Fibrilación ventricular gruesa',
      distractors: ['Fibrilación ventricular fina', 'Asistolia', 'TV polimorfa'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La FV gruesa tiene mayor amplitud y mejor probabilidad de respuesta al choque.',
      'Es ritmo desfibrilable: DEA inmediata.',
      'La amplitud suele disminuir con el tiempo sin RCP efectiva.',
      'Diferenciarla de una asistolia o de una derivación desconectada.',
    ],
    pitfalls: ['Confundir la FV fina con asistolia.', 'No priorizar la desfibrilación inmediata.'],
    refs: [109, 114, 122],
  },
  {
    id: 'K05',
    group: 'K',
    category: 'ventricular',
    title: 'Fibrilación ventricular fina',
    difficulty: 3,
    vignette: {
      age: 73,
      sex: 'F',
      history:
        'Paciente con paro prolongado; el monitor muestra una línea ondulada de muy baja amplitud.',
      vitals: 'PA —, FC —',
      troponin: 'hs-cTnT 95 ng/L',
    },
    scenario: {
      seed: 745,
      durationS: 10,
      rhythm: { type: 'vf', coarse: false },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Fibrilación ventricular fina',
      distractors: ['Asistolia', 'Fibrilación ventricular gruesa', 'Derivación desconectada'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La FV fina puede confundirse con asistolia en derivaciones de bajo voltaje.',
      'Antes de declarar asistolia, comprobar derivaciones y ganancia.',
      'La desfibrilación sigue indicada si se sospecha FV.',
      'La amplitud no descarta una etiología reversible.',
    ],
    pitfalls: [
      'Llamarla asistolia sin descartar FV fina.',
      'Suspender RCP sin comprobar la calidad de la señal.',
    ],
    refs: [109, 114, 122],
  },
  {
    id: 'K06',
    group: 'K',
    category: 'ventricular',
    title: 'Asistolia',
    difficulty: 3,
    vignette: {
      age: 84,
      sex: 'M',
      history: 'Paciente en paro; el registro muestra una línea basal sin actividad ventricular.',
      vitals: 'PA —, FC —',
      troponin: 'hs-cTnT 110 ng/L',
    },
    scenario: {
      seed: 746,
      durationS: 10,
      rhythm: { type: 'asystole' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'pacing'],
      diagnosis: 'Asistolia',
      distractors: [
        'Derivación desconectada',
        'Fibrilación ventricular fina',
        'Bloqueo AV completo',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La asistolia no es desfibrilable: RCP y causas reversibles.',
      'Confirmar con varias derivaciones antes de declararla.',
      'Buscar P o actividad auricular residual.',
      'Descartar artefacto por desconexión de electrodos.',
    ],
    pitfalls: [
      'Confundir una FV fina con asistolia.',
      'No comprobar la calidad de la señal en más de una derivación.',
    ],
    refs: [109, 114, 122],
  },
];
