import type { CaseDefinition } from './types.js';

/** Group L — marcapasos. docs/CASES.md §L. */
export const GROUP_L: CaseDefinition[] = [
  {
    id: 'L01',
    group: 'L',
    category: 'marcapasos',
    title: 'Marcapasos auricular (AAI)',
    difficulty: 2,
    vignette: {
      age: 76,
      sex: 'F',
      history: 'Paciente con marcapasos por disfunción sinusal; ECG de control ambulatorio.',
      vitals: 'PA 124/76, FC 60',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 751,
      durationS: 10,
      rhythm: { type: 'paced', mode: 'AAI', rateBpm: 60 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pacing'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Marcapasos auricular AAI',
      distractors: ['Marcapasos ventricular VVI', 'Marcapasos dual DDD', 'Ritmo de la unión'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La espiga precede a la P y luego conduce normalmente al ventrículo.',
      'AAI conserva la activación ventricular intrínseca.',
      'Comprobar sensibilidad y captura auricular.',
      'No confundir la espiga auricular con un artefacto.',
    ],
    pitfalls: [
      'No identificar la espiga por su baja amplitud.',
      'Confundir el ritmo con un escape juntoral.',
    ],
    refs: [115, 126],
  },
  {
    id: 'L02',
    group: 'L',
    category: 'marcapasos',
    title: 'Marcapasos ventricular (VVI)',
    difficulty: 2,
    vignette: {
      age: 82,
      sex: 'M',
      history: 'Paciente con FA y marcapasos ventricular; ECG de urgencias por mareo.',
      vitals: 'PA 110/64, FC 60',
      troponin: 'hs-cTnT 20 ng/L',
    },
    scenario: {
      seed: 752,
      durationS: 10,
      rhythm: { type: 'paced', mode: 'VVI', rateBpm: 60 },
      conduction: 'normal',
      sources: [],
      beatOverrides: { jNotchMv: 0.1 },
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pacing', 'wide-qrs'],
      negativeFindings: ['stemi-udmi4', 'sgarbossa', 'sgarbossa-modified', 'barcelona'],
      diagnosis: 'Marcapasos ventricular VVI',
      distractors: ['Marcapasos auricular AAI', 'Marcapasos dual DDD', 'Ritmo idioventricular'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La espiga ventricular precede al QRS ancho capturado.',
      'VVI estimula el ventrículo y lo inhibe si detecta actividad propia.',
      'El QRS marcapaseado suele tener morfología tipo BRI.',
      'El marcapasos ventricular puede enmascarar el diagnóstico isquémico.',
    ],
    pitfalls: [
      'No reconocer la espiga ventricular en el complejo ancho.',
      'Descartar isquemia por el QRS ancho sin revisar la espiga.',
    ],
    refs: [115, 126],
  },
  {
    id: 'L03',
    group: 'L',
    category: 'marcapasos',
    title: 'Marcapasos dual (DDD)',
    difficulty: 3,
    vignette: {
      age: 79,
      sex: 'F',
      history: 'Paciente con marcapasos bicameral; ECG de control tras ajuste del intervalo AV.',
      vitals: 'PA 120/72, FC 70',
      troponin: 'hs-cTnT 14 ng/L',
    },
    scenario: {
      seed: 753,
      durationS: 10,
      rhythm: { type: 'paced', mode: 'DDD', rateBpm: 70, avDelayMs: 160 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pacing', 'wide-qrs'],
      negativeFindings: ['stemi-udmi4', 'sgarbossa', 'sgarbossa-modified', 'barcelona'],
      diagnosis: 'Marcapasos dual DDD',
      distractors: [
        'Marcapasos ventricular VVI',
        'Marcapasos auricular AAI',
        'Bloqueo AV completo',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'DDD puede estimular aurícula y ventrículo con un retardo AV programado.',
      'La captura ventricular sigue a la auricular si el conduction intrínseco es insuficiente.',
      'Comprobar espigas, latidos capturados y modo de sensado.',
      'El retardo AV se ajusta según función AV y programación.',
    ],
    pitfalls: [
      'Confundir la secuencia AV con una arritmia organizada.',
      'No distinguir entre captura auricular y ventricular.',
    ],
    refs: [115, 126],
  },
];
