import type { CaseDefinition } from './types.js';

/** Group C — isquemia sin oclusión (NOMI). docs/CASES.md §C. */
export const GROUP_C: CaseDefinition[] = [
  {
    id: 'C01',
    group: 'C',
    title: 'STD difusa + STE aVR por demanda',
    difficulty: 2,
    vignette: {
      age: 81,
      sex: 'F',
      history: 'Mujer de 81 años con taquicardia de 130 lpm y anemia aguda (Hb 6.5).',
      vitals: 'PA 95/55, FC 130, SatO2 94 %',
      troponin: 'hs-cTnT 65 ng/L',
    },
    scenario: {
      seed: 301,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 130 },
      conduction: 'normal',
      sources: [{ territory: 'subendocardial', st: -0.15, refLead: 'V5', shape: 'straight' }],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['avr-diffuse-std'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'sin culpable / 3 vasos estable',
    teachingPoints: [
      'STD difusa + STE aVR = isquemia subendocárdica, no necesariamente oclusión.',
      'Corregir la causa de la demanda (anemia, taquicardia) es el tratamiento.',
      'La angiografía urgente solo si hay sospecha de TCI/3 vasos agudo.',
      'La isquemia por demanda no requiere oclusión: es un desequilibrio oferta/demanda.',
    ],
    pitfalls: [
      'Activar el código infarto en toda STD difusa sin valorar el contexto.',
      'No corregir la causa desencadenante (anemia, taquicardia).',
    ],
    refs: [56, 57, 37],
  },
  {
    id: 'C02',
    group: 'C',
    title: 'Tronco común subtotal',
    difficulty: 3,
    vignette: {
      age: 70,
      sex: 'M',
      history: 'Varón de 70 años con dolor torácico, shock y sudoración profusa.',
      vitals: 'PA 80/50, FC 110, SatO2 91 %',
      troponin: 'hs-cTnT 450 ng/L',
    },
    scenario: {
      seed: 302,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 110 },
      conduction: 'normal',
      sources: [
        { territory: 'subendocardial', st: -0.25, refLead: 'V5', shape: 'straight' },
        { territory: 'anteroseptal', st: 0.1, refLead: 'V1', shape: 'straight' },
      ],
    },
    expected: {
      omi: true,
      activateCathLab: true,
      culprit: 'TCI 95 %',
      positiveFindings: ['avr-diffuse-std'],
      negativeFindings: ['rv-involvement'],
    },
    angiography: 'TCI 95 %',
    teachingPoints: [
      'STD difusa + STE aVR + shock = sospechar tronco común.',
      'La regla avr-diffuse-std no distingue demanda de TCI: el shock lo define.',
      'Emergencia: angiografía inmediata y soporte hemodinámico.',
      'El tronco común subtotal es una emergencia quirúrgica/angiográfica inmediata.',
    ],
    pitfalls: [
      'Asumir que la STD difusa es solo demanda ante un paciente inestable.',
      'Administrar betabloqueo o vasodilatadores en shock.',
    ],
    refs: [56, 57, 53],
  },
  {
    id: 'C03',
    group: 'C',
    title: 'NSTEMI verdadero, STD lateral',
    difficulty: 2,
    vignette: {
      age: 64,
      sex: 'M',
      history: 'Varón de 64 años con dolor de 4 horas, ahora en descenso espontáneo.',
      vitals: 'PA 135/85, FC 82',
      troponin: 'hs-cTnT 300 ng/L',
      symptomsOnsetMin: 240,
    },
    scenario: {
      seed: 303,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 82 },
      conduction: 'normal',
      sources: [{ territory: 'subendocardial', st: -0.08, refLead: 'V5', shape: 'straight' }],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      culprit: 'CX 80 % TIMI 3',
      positiveFindings: [],
      negativeFindings: ['stemi-udmi4', 'omi-composite'],
    },
    angiography: 'CX 80 % TIMI 3',
    teachingPoints: [
      'La STD lateral con troponina alta es NSTEMI: angiografía en 24–72 h según GRACE.',
      'Sin signos de oclusión el manejo inicial es médico.',
      'Vigilar evolución: la STD puede transformarse en OMI.',
      'El NSTEMI con STD persistente puede evolucionar a oclusión: vigilancia estrecha.',
    ],
    pitfalls: [
      'Relajar la vigilancia cuando el dolor remite.',
      'No seriar ECG y troponina en NSTEMI de alto riesgo.',
    ],
    refs: [53, 11, 12],
  },
  {
    id: 'C04',
    group: 'C',
    title: 'Isquemia en TSV',
    difficulty: 2,
    vignette: {
      age: 45,
      sex: 'F',
      history:
        'Mujer de 45 años con palpitaciones; taquicardia regular rápida que cede con maniobras vagales.',
      vitals: 'PA 100/65, FC 180',
      troponin: 'hs-cTnT 22 ng/L',
    },
    scenario: {
      seed: 304,
      durationS: 5,
      rhythm: { type: 'svt', hrBpm: 180 },
      conduction: 'normal',
      sources: [{ territory: 'subendocardial', st: -0.12, refLead: 'V5', shape: 'straight' }],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['avr-diffuse-std'],
      negativeFindings: ['stemi-udmi4'],
    },
    angiography: 'normal',
    teachingPoints: [
      'La STD por taquicardia suele revertir al frenar la frecuencia.',
      'Repetir ECG tras cardioversión antes de atribuir isquemia.',
      'La demanda aumentada produce el patrón subendocárdico.',
      'La STD durante TSV puede ser funcional: repetir el ECG tras la reversión.',
    ],
    pitfalls: [
      'Diagnosticar isquemia coronaria sin valorar el ritmo.',
      'No reevaluar el segmento ST una vez controlada la frecuencia.',
    ],
    refs: [56, 57],
  },
];
