import type { CaseDefinition } from './types.js';

/** Group J — conducción intraventricular. docs/CASES.md §J. */
export const GROUP_J: CaseDefinition[] = [
  {
    id: 'J01',
    group: 'J',
    category: 'conduccion',
    title: 'Bloqueo completo de rama derecha',
    difficulty: 1,
    vignette: {
      age: 67,
      sex: 'M',
      history: 'Paciente con hipertensión; hallazgo incidental de QRS ancho en el ECG anual.',
      vitals: 'PA 134/80, FC 74',
      troponin: 'hs-cTnT 12 ng/L',
    },
    scenario: {
      seed: 731,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 74 },
      conduction: 'rbbb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [
        'wide-qrs',
        'bundle-branch-morphology',
        'stemi-udmi4',
        'reciprocal-avl',
        'pathological-q',
        'axis-deviation',
      ],
      negativeFindings: ['av-dissociation'],
      rulesMiss:
        'La morfología rSR′ y la discordancia del BRD activan las reglas de oclusión; el BRD es la lesión real.',
      diagnosis: 'Bloqueo completo de rama derecha',
      distractors: [
        'Bloqueo completo de rama izquierda',
        'Hemibloqueo anterior',
        'Síndrome de Brugada',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'QRS ≥ 120 ms con rSR′ en V1 y S ancha en I/V6 define BRD.',
      'La activación ventricular derecha es tardía y termina la QRS.',
      'Suele ser benigno si aislado y asintomático.',
      'Las T discordantes son secundarias y esperables.',
    ],
    pitfalls: [
      'Confundir el R′ de V1 con isquemia posterior o Brugada.',
      'No reconocer que el BRD puede enmascarar el diagnóstico de STEMI.',
    ],
    refs: [110, 126],
  },
  {
    id: 'J02',
    group: 'J',
    category: 'conduccion',
    title: 'Bloqueo incompleto de rama derecha',
    difficulty: 1,
    vignette: {
      age: 28,
      sex: 'F',
      history: 'Paciente joven sana; ECG realizado por chequeo deportivo.',
      vitals: 'PA 112/70, FC 68',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 732,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 68 },
      conduction: 'irbbb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [
        'axis-deviation',
        'stemi-udmi4',
        'rv-involvement',
        'reciprocal-avl',
        'pathological-q',
      ],
      negativeFindings: ['wide-qrs'],
      rulesMiss:
        'La r′ en V1 del BRD incompleto imita un patrón posterior y activa las reglas de oclusión; es una variante de conducción.',
      diagnosis: 'Bloqueo incompleto de rama derecha',
      distractors: ['Bloqueo completo de rama derecha', 'Normalidad', 'Síndrome de Brugada'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El BRD incompleto tiene morfología de BRD pero QRS < 120 ms.',
      'Frecuente en jóvenes, variantes normales y aumento de volumen VD.',
      'Suele ser un hallazgo, no una enfermedad.',
      'Diferenciar de la variante normal con R′ pequeña en V1.',
    ],
    pitfalls: [
      'Confundirlo con BRD completo por la presencia de R′.',
      'Sobrediagnosticar patología en un corazón normal.',
    ],
    refs: [110, 126],
  },
  {
    id: 'J03',
    group: 'J',
    category: 'conduccion',
    title: 'Bloqueo completo de rama izquierda sin isquemia',
    difficulty: 2,
    vignette: {
      age: 74,
      sex: 'M',
      history: 'Paciente con insuficiencia cardiaca crónica; ECG de control sin dolor torácico.',
      vitals: 'PA 122/76, FC 76',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 733,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 76 },
      conduction: 'lbbb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['wide-qrs', 'bundle-branch-morphology'],
      negativeFindings: ['sgarbossa', 'sgarbossa-modified', 'barcelona', 'omi-composite'],
      diagnosis: 'Bloqueo completo de rama izquierda',
      distractors: [
        'Bloqueo completo de rama derecha',
        'Infarto anterior',
        'Hipertrofia ventricular izquierda',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'QRS ancho, negativo dominante en V1 y positivo ancho en V6 definen BRI.',
      'El BRI crónico sin síntomas no implica isquemia.',
      'Los criterios de Sgarbossa modificados son el punto de partida ante dolor.',
      'Un BRI nuevo con dolor torácico sigue siendo una urgencia.',
    ],
    pitfalls: [
      'Asumir isquemia solo por la discordancia secundaria del BRI.',
      'Ignorar que un BRI de novo puede ocultar una oclusión aguda.',
    ],
    refs: [110, 52, 53],
  },
  {
    id: 'J04',
    group: 'J',
    category: 'conduccion',
    title: 'Hemibloqueo anterior izquierdo',
    difficulty: 2,
    vignette: {
      age: 63,
      sex: 'M',
      history: 'Paciente con hipertensión; ECG con eje desviado en la revisión.',
      vitals: 'PA 140/86, FC 72',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 734,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'lafb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['axis-deviation'],
      negativeFindings: ['wide-qrs', 'omi-composite'],
      diagnosis: 'Hemibloqueo anterior izquierdo',
      distractors: ['Bloqueo completo de rama izquierda', 'Hemibloqueo posterior', 'Normalidad'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El HBAI produce eje frontal entre −45° y −90°.',
      'La QRS sigue siendo estrecha aunque ligeramente prolongada.',
      'Patrón qR en I/aVL y rS en II/III/aVF.',
      'Suele ser un hallazgo aislado, pero puede marcar fibrosis del Haz.',
    ],
    pitfalls: [
      'No medir el eje y confundirlo con normalidad.',
      'Atribuir el eje izquierdo a un infarto inferior previo sin más datos.',
    ],
    refs: [110, 126],
  },
  {
    id: 'J05',
    group: 'J',
    category: 'conduccion',
    title: 'Hemibloqueo posterior izquierdo',
    difficulty: 2,
    vignette: {
      age: 66,
      sex: 'F',
      history: 'Paciente con enfermedad pulmonar obstructiva; ECG con eje derecho en control.',
      vitals: 'PA 126/78, FC 70',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 735,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'lpfb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['axis-deviation'],
      negativeFindings: ['wide-qrs', 'omi-composite'],
      diagnosis: 'Hemibloqueo posterior izquierdo',
      distractors: ['Hipertrofia ventricular derecha', 'Dextrocardia', 'Normalidad'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El HBPI produce eje frontal > +90° con QRS estrecha.',
      'Es diagnóstico de exclusión: descartar HVD y otras causas de eje derecho.',
      'Patrón rS en I/aVL y qR en II/III/aVF.',
      'Mucho menos frecuente que el HBAI.',
    ],
    pitfalls: [
      'Diagnosticarlo sin descartar primero la HVD.',
      'Confundirlo con una variante de ECG normal en jóvenes.',
    ],
    refs: [110, 126],
  },
  {
    id: 'J06',
    group: 'J',
    category: 'conduccion',
    title: 'Bloqueo bifascicular (BRD + HBAI)',
    difficulty: 3,
    vignette: {
      age: 79,
      sex: 'M',
      history: 'Paciente con síncope reciente y fibrosis del sistema específico; ECG ambulatorio.',
      vitals: 'PA 120/72, FC 60',
      troponin: 'hs-cTnT 20 ng/L',
    },
    scenario: {
      seed: 736,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 60 },
      conduction: 'rbbb-lafb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pathological-q'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Bloqueo bifascicular BRD + HBAI',
      distractors: [
        'Bloqueo completo de rama derecha',
        'Bloqueo completo de rama izquierda',
        'Bloqueo AV Mobitz II',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Combina QRS ancho con morfología de BRD y eje izquierdo marcado.',
      'Indica compromiso de dos fascículos del sistema de conducción.',
      'La presencia de síncope eleva la sospecha de progresión a bloqueo completo.',
      'Merece estudio electrofisiológico si sintomático.',
    ],
    pitfalls: [
      'Mirar solo V1 y no medir el eje.',
      'No valorar el riesgo de progresión ante síncope.',
    ],
    refs: [110, 125],
  },
  {
    id: 'J07',
    group: 'J',
    category: 'conduccion',
    title: '«Trifascicular» (BRD + HBAI + BAV 1.º)',
    difficulty: 3,
    vignette: {
      age: 81,
      sex: 'F',
      history: 'Paciente con enfermedad degenerativa del sistema de conducción; ECG de control.',
      vitals: 'PA 118/70, FC 58',
      troponin: 'hs-cTnT 16 ng/L',
    },
    scenario: {
      seed: 737,
      durationS: 10,
      rhythm: { type: 'av-block-1', hrBpm: 58, prMs: 230 },
      conduction: 'rbbb-lafb',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pr-prolonged'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Bloqueo trifascicular (BRD + HBAI + BAV 1.º)',
      distractors: [
        'Bloqueo bifascicular',
        'Bloqueo completo de rama derecha',
        'Bloqueo AV Mobitz II',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'BRD + eje izquierdo + PR largo sugiere compromiso de los tres fascículos.',
      'No equivale a bloqueo AV completo, pero indica mayor riesgo.',
      'La frecuencia puede ser solo levemente menor.',
      'Suele requerir marcapasos si sintomático o progresivo.',
    ],
    pitfalls: [
      'Subestimarlo como bifascicular por no mirar el PR.',
      'Confundir el PR largo con un simple primer grado aislado.',
    ],
    refs: [110, 125],
  },
  {
    id: 'J08',
    group: 'J',
    category: 'conduccion',
    title: 'Preexcitación ventricular (WPW)',
    difficulty: 2,
    vignette: {
      age: 22,
      sex: 'M',
      history: 'Paciente joven con palpitaciones paroxísticas; ECG basal de urgencias.',
      vitals: 'PA 122/74, FC 78',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 738,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 78 },
      conduction: 'wpw',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pr-short'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Síndrome de preexcitación (WPW)',
      distractors: ['Bloqueo AV de primer grado', 'Bloqueo completo de rama derecha', 'Normalidad'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'PR corto, delta wave y QRS ligeramente ancho sugieren vía accesoria.',
      'El WPW aumenta el riesgo de TSV y de FA rápida con conducción aberrante.',
      'Buscar la onda delta en los primeros 40 ms del QRS.',
      'Derivación a electrofisiología tras un episodio documentado.',
    ],
    pitfalls: [
      'Pasar por alto la onda delta sutil.',
      'No advertir el riesgo si aparece FA en un WPW.',
    ],
    refs: [110, 108],
  },
];
