import type { CaseDefinition } from './types.js';

/** Group H — ectopia. docs/CASES.md §H. */
export const GROUP_H: CaseDefinition[] = [
  {
    id: 'H01',
    group: 'H',
    category: 'ectopia',
    title: 'Extrasístole auricular aislada',
    difficulty: 1,
    vignette: {
      age: 45,
      sex: 'F',
      history: 'Paciente con sensación ocasional de vuelco cardíaco; sin cardiopatía conocida.',
      vitals: 'PA 122/76, FC 72',
      troponin: 'no indicada',
    },
    scenario: {
      seed: 711,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 72 },
      ectopy: { kind: 'pac', pattern: 'isolated', perMin: 6 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'av-dissociation', 'flutter-waves'],
      diagnosis: 'Extrasístole auricular aislada',
      distractors: ['Extrasístole ventricular', 'Bloqueo AV Mobitz I', 'Arritmia sinusal'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La ESA adelanta el ritmo con una P′ de morfología distinta.',
      'La pausa post-ESA es no compensatoria: el nodo sinusal se reinicia.',
      'Suelen ser benignas; estudiar si frecuentes o sintomáticas.',
      'Una ESA bloqueada simula una pausa: mirar la T precedente.',
    ],
    pitfalls: [
      'Confundir la pausa no compensatoria con un bloqueo AV.',
      'No reconocer la P′ deformando la onda T anterior.',
    ],
    refs: [126, 112],
  },
  {
    id: 'H02',
    group: 'H',
    category: 'ectopia',
    title: 'Extrasístole ventricular aislada',
    difficulty: 1,
    vignette: {
      age: 38,
      sex: 'M',
      history: 'Paciente con palpitaciones aisladas y ECG de control; sin síntomas de esfuerzo.',
      vitals: 'PA 124/78, FC 70',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 712,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 70 },
      ectopy: { kind: 'pvc', pattern: 'isolated', perMin: 6, pvcOrigin: 'rv' },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Extrasístole ventricular aislada',
      distractors: [
        'Extrasístole auricular aberrante',
        'Bigeminismo ventricular',
        'Fusión ventricular',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'QRS precoz, ancho y sin P precedente, seguido de pausa compensatoria completa.',
      'La T del ESV es discordante: opuesta al QRS.',
      'Origen VD: patrón tipo BRI con eje inferior.',
      'La ESV aislada sin cardiopatía estructural es benigna.',
    ],
    pitfalls: [
      'Leer la T discordante del ESV como isquemia.',
      'No comprobar la pausa compensatoria para diferenciar ESV de ESA aberrante.',
    ],
    refs: [109, 126],
  },
  {
    id: 'H03',
    group: 'H',
    category: 'ectopia',
    title: 'Bigeminismo ventricular',
    difficulty: 1,
    vignette: {
      age: 52,
      sex: 'M',
      history: 'Paciente con extrasistolia sintomática; Holter previo con alta carga de ESV.',
      vitals: 'PA 130/82, FC 66',
      troponin: 'hs-cTnT 11 ng/L',
    },
    scenario: {
      seed: 713,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 72 },
      ectopy: { kind: 'pvc', pattern: 'bigeminy', couplingMs: 450 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular'],
      negativeFindings: ['omi-composite', 'av-dissociation'],
      diagnosis: 'Bigeminismo ventricular',
      distractors: [
        'Trigeminismo ventricular',
        'Taquicardia ventricular no sostenida',
        'Alternans eléctrico',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Alternancia estricta latido sinusal–ESV: cada sinusal seguido de un prematuro.',
      'El acoplamiento fijo sugiere mecanismo de reentrada microscópica.',
      'Carga elevada sostenida puede inducir miocardiopatía por extrasistolia.',
      'Buscar cardiopatía estructural si la carga es alta.',
    ],
    pitfalls: [
      'Interpretar cada segundo latido como bloqueo por la pausa aparente.',
      'Omitir la cuantificación de carga en Holter.',
    ],
    refs: [109, 126],
  },
  {
    id: 'H04',
    group: 'H',
    category: 'ectopia',
    title: 'Trigeminismo ventricular',
    difficulty: 1,
    vignette: {
      age: 60,
      sex: 'F',
      history: 'Paciente con sensación de latidos salteados tras un cuadro gripal reciente.',
      vitals: 'PA 126/78, FC 74',
      troponin: 'hs-cTnT 14 ng/L',
    },
    scenario: {
      seed: 714,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 74 },
      ectopy: { kind: 'pvc', pattern: 'trigeminy', couplingMs: 450 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular'],
      negativeFindings: ['omi-composite', 'av-dissociation'],
      diagnosis: 'Trigeminismo ventricular',
      distractors: ['Bigeminismo ventricular', 'Bloqueo AV Mobitz I', 'FA con respuesta irregular'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Cada tercer latido es un ESV: dos sinusales + uno prematuro.',
      'El patrón periódico ayuda a distinguirlo de una irregularidad caótica.',
      'Valorar número, síntomas y función ventricular en el estudio.',
      'Los antiarrítmicos se reservan para alta carga o síntomas.',
    ],
    pitfalls: [
      'Confundir el patrón periódico con arritmia auricular irregular.',
      'Atribuir los latidos extra a fármacos sin revisar potasio/magnesio.',
    ],
    refs: [109, 126],
  },
  {
    id: 'H05',
    group: 'H',
    category: 'ectopia',
    title: 'Dupla ventricular',
    difficulty: 2,
    vignette: {
      age: 66,
      sex: 'M',
      history:
        'Paciente con antecedente de infarto previo; durante la monitorización aparecen parejas de latidos prematuros.',
      vitals: 'PA 134/80, FC 70',
      troponin: 'hs-cTnT 30 ng/L',
    },
    scenario: {
      seed: 715,
      durationS: 10,
      rhythm: { type: 'sinus', hrBpm: 70 },
      ectopy: { kind: 'pvc', pattern: 'couplet', couplingMs: 430 },
      conduction: 'normal',
      sources: [],
      variability: false,
    },
    ecgAtMin: 0,
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['rr-irregular'],
      negativeFindings: ['omi-composite'],
      diagnosis: 'Dupla ventricular (dos ESV consecutivos)',
      distractors: [
        'Bigeminismo ventricular',
        'Taquicardia ventricular sostenida',
        'Aberrancia supraventricular',
      ],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'Dos ESV consecutivos definen una dupla; tres o más, TV no sostenida.',
      'En cardiopatía estructural aumenta el riesgo arrítmico.',
      'El origen VD produce morfología tipo BRI con eje inferior.',
      'La pausa tras la dupla puede ser larga por reinicio sinusal.',
    ],
    pitfalls: [
      'Llamar bigeminismo a una dupla con pausa larga.',
      'No valorar el contexto isquémico del paciente.',
    ],
    refs: [109, 122],
  },
];
