import type { CaseDefinition } from './types.js';
import { hyperkalemiaOverrides } from '../engine/index.js';

/** Group D — mimics (controles negativos). docs/CASES.md §D. */
export const GROUP_D: CaseDefinition[] = [
  {
    id: 'D01',
    group: 'D',
    category: 'oclusion',
    title: 'Repolarización precoz',
    difficulty: 2,
    vignette: {
      age: 24,
      sex: 'M',
      history:
        'Varón de 24 años con dolor pleurítico que aumenta con la inspiración. Sin antecedentes.',
      vitals: 'PA 120/75, FC 62',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 401,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 62 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.45, refLead: 'V3', shape: 'concave', hyperacuteT: 0 },
      ],
      beatOverrides: { jNotchMv: 0.06, aTScale: 1.05, qtc: 380, rScale: 1.4 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['stemi-udmi4', 'terminal-qrs-distortion'],
      negativeFindings: ['smith-4v', 'hyperacute-t'],
      rulesMiss:
        'Falso STEMI+: los criterios UDMI4 se cumplen técnicamente; el diagnóstico de repolarización precoz es morfológico (concavidad, muesca J, R alta, QTc corto, ausencia de recíprocos).',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La RP tiene STE cóncavo, muesca en J y R altas en V4.',
      'Smith 4v suele ser negativo en RP por la R alta y el QTc corto.',
      'Puede cumplir criterios STEMI técnicos: el contexto decide.',
      'El contexto de edad, sexo y ausencia de recíproca orienta a repolarización precoz.',
    ],
    pitfalls: [
      'STE técnico en V2–V3 no es oclusión si hay J-notch y concavidad.',
      'STE técnico en V2–V3 no es oclusión si hay J-notch y concavidad.',
      'Activar el código en un joven sano por un umbral aislado.',
    ],
    refs: [66, 67, 80],
  },
  {
    id: 'D02',
    group: 'D',
    category: 'oclusion',
    title: 'Pericarditis',
    difficulty: 2,
    vignette: {
      age: 31,
      sex: 'M',
      history: 'Varón de 31 años con dolor postural que mejora al inclinarse.',
      vitals: 'PA 120/80, FC 78',
      troponin: 'hs-cTnT 40 ng/L',
    },
    scenario: {
      seed: 402,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 78 },
      variability: false,
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.03, refLead: 'V3', shape: 'concave' },
        { territory: 'inferior-lcx', st: 0.04, refLead: 'II', shape: 'concave' },
        { territory: 'lateral', st: 0.02, refLead: 'V6', shape: 'concave' },
      ],
      beatOverrides: { prDepressionMv: 0.08, qtc: 380 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'STE difuso cóncavo + depresión del PR + ausencia de recíproca = pericarditis.',
      'El STE de pericarditis no respeta un territorio vascular.',
      'aVR sin STE ayuda frente a isquemia subendocárdica.',
      'El dolor postural y la depresión del PR orientan a pericarditis.',
    ],
    pitfalls: [
      'Confundir el STE difuso con una OMI extenso.',
      'Omitir la auscultación del roce pericárdico.',
    ],
    refs: [69, 88, 19],
  },
  {
    id: 'D03',
    group: 'D',
    category: 'oclusion',
    title: 'HVI con strain',
    difficulty: 2,
    vignette: {
      age: 70,
      sex: 'F',
      history:
        'Mujer de 70 años, hipertensa de larga evolución, con disnea de esfuerzo progresiva.',
      vitals: 'PA 165/95, FC 84',
      troponin: 'hs-cTnT 18 ng/L',
    },
    scenario: {
      seed: 403,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 84 },
      conduction: 'lvh-strain',
      beatOverrides: { aTScale: 1.45 },
      sources: [],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss:
        'El strain de HVI produce STE discordante proporcional en V1–V3 que cumple umbrales UDMI4; la desproporción ST/QRS (discordancia proporcional) no está codificada como regla, por lo que omi-composite da un falso positivo deliberado.',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El strain de HVI produce STE discordante proporcional en V1–V3.',
      'La desproporción ST/QRS distingue strain de oclusión.',
      'La historia (HTA, voltajes) orienta el diagnóstico.',
      'La discordancia ST/T del strain es proporcional al voltaje del QRS.',
    ],
    pitfalls: [
      'Interpretar la discordancia del strain como isquemia.',
      'No ponderar el tamaño del QRS al valorar el ST.',
    ],
    refs: [78, 33],
  },
  {
    id: 'D04',
    group: 'D',
    category: 'oclusion',
    title: 'LBBB sin isquemia',
    difficulty: 2,
    vignette: {
      age: 78,
      sex: 'M',
      history: 'Varón de 78 años con LBBB crónico, chequeo sin dolor.',
      vitals: 'PA 135/80, FC 72',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 404,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'lbbb',
      sources: [],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['sgarbossa', 'sgarbossa-modified', 'barcelona', 'omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El LBBB tiene discordancia fisiológica proporcional al QRS.',
      'Sgarbossa y BARCELONA son negativos sin isquemia.',
      'El exceso de discordancia (ST/S) es lo que delata la OMI.',
      'En el LBBB sin isquemia la discordancia respeta la proporción fisiológica.',
    ],
    pitfalls: [
      'Diagnosticar isquemia por la discordancia fisiológica del LBBB.',
      'No aplicar los criterios específicos en pacientes sintomáticos.',
    ],
    refs: [61, 62, 60],
  },
  {
    id: 'D05',
    group: 'D',
    category: 'oclusion',
    title: 'Hiperpotasemia',
    difficulty: 2,
    vignette: {
      age: 60,
      sex: 'M',
      history:
        'Varón de 60 años con enfermedad renal crónica; potasio sérico de 7.2 en la analítica urgente.',
      vitals: 'PA 140/85, FC 70',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 405,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 70 },
      conduction: 'normal',
      sources: [],
      beatOverrides: hyperkalemiaOverrides(),
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'hyperacute-t'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La T hiperkalemia es estrecha y simétrica; la hiperaguda de OMI es ancha.',
      'El score hyperacute-t pondera el área T/QRS: la T estrecha puntúa bajo.',
      'Correlacionar con K+ sérico y ancho de QRS.',
      'La hiperpotasemia puede simular T hiperagudas, pero la T del potasio es estrecha y simétrica con QRS ensanchado.',
    ],
    pitfalls: [
      'Confundir la T hiperkalémica con la hiperaguda isquémica.',
      'No pedir ionograma ante un ECG con T picudas.',
    ],
    refs: [77],
  },
  {
    id: 'D06',
    group: 'D',
    category: 'oclusion',
    title: 'Brugada tipo 1',
    difficulty: 3,
    vignette: {
      age: 42,
      sex: 'M',
      history:
        'Varón de 42 años con síncope sin prodromo mientras veía la televisión. Sin cardiopatía conocida.',
      vitals: 'PA 125/80, FC 75',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 406,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 75 },
      conduction: 'normal',
      sources: [{ territory: 'rvot', st: 0.3, refLead: 'V2', shape: 'convex', tInversion: 1 }],
      acquisition: { placement: 'v1v2-high' },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss:
        'La morfología coved con STE ≥ umbral en V1–V2 es indistinguible del STEMI anterior por criterios UDMI4: el diagnóstico de Brugada es clínico-electrocardiográfico (T negativa, V1–V2 altos), no de reglas de oclusión.',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El coved de Brugada desciende a T negativa sin recíproca inferior.',
      'La colocación alta de V1–V2 desenmascara el patrón.',
      'El síncope + Brugada tipo 1 tiene implicaciones de riesgo propias.',
      'El patrón coved de Brugada tipo 1 es diagnóstico por morfología, no por criterios de lesión.',
    ],
    pitfalls: [
      'Confundir el patrón Brugada con un STE anteroseptal.',
      'No retirar la colocación alta de electrodos antes de descartar artefacto.',
    ],
    refs: [79, 33],
  },
  {
    id: 'D07',
    group: 'D',
    category: 'oclusion',
    title: 'Takotsubo',
    difficulty: 3,
    vignette: {
      age: 67,
      sex: 'F',
      history: 'Mujer de 67 años tras estrés emocional intenso (fallecimiento de un familiar).',
      vitals: 'PA 110/70, FC 96',
      troponin: 'hs-cTnT 140 ng/L',
    },
    scenario: {
      seed: 407,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 96 },
      conduction: 'normal',
      sources: [
        { territory: 'anteroapical', st: 0.15, refLead: 'V4', shape: 'concave' },
        { territory: 'inferior-lcx', st: 0.08, refLead: 'II', shape: 'concave' },
      ],
      beatOverrides: { qtc: 500 },
    },
    expected: {
      omi: false,
      activateCathLab: true,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss: 'Indistinguible de OMI por ECG: la angiografía (sin culpable) es el diagnóstico.',
    },
    angiography: 'coronarias limpias; ventriculografía apical balón',
    teachingPoints: [
      'Takotsubo puede cumplir criterios STEMI: angiografía inmediata.',
      'El QTc prolongado y la discordancia edad/severidad son pistas.',
      'Diagnóstico de exclusión tras coronariografía.',
      'El takotsubo es un diagnóstico de exclusión tras coronariografía normal.',
    ],
    pitfalls: [
      'Asumir oclusión solo por el contexto emocional sin descartarla.',
      'Olvidar el seguimiento del QTc en takotsubo.',
    ],
    refs: [74, 75],
  },
  {
    id: 'D08',
    group: 'D',
    category: 'oclusion',
    title: 'Miocarditis',
    difficulty: 2,
    vignette: {
      age: 28,
      sex: 'M',
      history:
        'Varón de 28 años tras un cuadro viral febril hace 5 días; dolor torácico leve persistente.',
      vitals: 'PA 125/80, FC 88',
      troponin: 'hs-cTnT 350 ng/L',
    },
    scenario: {
      seed: 408,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 85 },
      ectopy: { kind: 'pvc', pattern: 'isolated', perMin: 4 },
      conduction: 'normal',
      sources: [
        { territory: 'anterior', st: 0.03, refLead: 'V3', shape: 'concave' },
        { territory: 'lateral', st: 0.03, refLead: 'V6', shape: 'concave' },
      ],
      beatOverrides: { qtc: 380 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La miocarditis difusa produce STE concavo multiterritorial.',
      'La troponina alta con ECG difuso no es oclusión focal.',
      'La RM cardiaca confirma el diagnóstico.',
      'La miocarditis muestra lesión difusa sin territorio vascular definido.',
    ],
    pitfalls: [
      'Interpretar el STE difuso como oclusión multivaso.',
      'No pedir RM cardiaca en la sospecha de miocarditis.',
    ],
    refs: [72, 88],
  },
  {
    id: 'D09',
    group: 'D',
    category: 'oclusion',
    title: 'Embolia pulmonar',
    difficulty: 3,
    vignette: {
      age: 50,
      sex: 'F',
      history:
        'Mujer de 50 años con disnea súbita, taquicardia y antecedente de inmovilización reciente.',
      vitals: 'PA 100/65, FC 115, SatO2 90 %',
      troponin: 'hs-cTnT 60 ng/L',
    },
    scenario: {
      seed: 409,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 115 },
      conduction: 'rbbb',
      sources: [{ territory: 'rv', st: 0.015, refLead: 'V1', shape: 'concave', tInversion: 0.8 }],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: [],
      rulesMiss:
        'S1Q3T3 + BRD de derechas produce un patrón pseudo-Aslanger (STE III aislado, STD lateral, STE en V3R–V4R por discordancia de la BRD) que cumple umbrales UDMI4 en las derivaciones derechas: la regla no discrimina la discordancia propia de la BRD.',
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La sobrecarga aguda del VD da T negativas en V1–V3 y BRD incompleto.',
      'Disnea + taquicardia + S1Q3T3 orientan a TEP, no a OMI.',
      'La angio-TC confirma; el ECG solo sugiere.',
      'La sobrecarga aguda del VD por TEP produce signos precordiales derechos sin oclusión coronaria.',
    ],
    pitfalls: [
      'Interpretar el patrón VD como infarto septal.',
      'No pedir angio-TC ante la sospecha de TEP.',
    ],
    refs: [76],
  },
  {
    id: 'D10',
    group: 'D',
    category: 'oclusion',
    title: 'Aneurisma VI (STE persistente)',
    difficulty: 3,
    vignette: {
      age: 66,
      sex: 'M',
      history:
        'Varón de 66 años con IAM anterior tratado hace 2 años; se revisa por control, sin dolor agudo.',
      vitals: 'PA 130/80, FC 76',
      troponin: 'hs-cTnT 16 ng/L',
    },
    scenario: {
      seed: 410,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 76 },
      conduction: 'normal',
      sources: [
        {
          territory: 'anterior',
          st: 0.1,
          refLead: 'V3',
          shape: 'straight',
          qLoss: 0.6,
          tInversion: 0.3,
        },
      ],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: ['pathological-q'],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'DA crónica con aneurisma apical',
    teachingPoints: [
      'El STE persistente con Q patológicas y baja relación T/QRS sugiere aneurisma.',
      'La amplitud T baja respecto al STE distingue aneurisma de OMI aguda.',
      'Comparar con ECGs antiguos es esencial.',
      'El aneurisma ventricular deja STE persistente con Q patológicas de larga evolución.',
    ],
    pitfalls: [
      'Confundir el STE persistente con una reoclusión aguda.',
      'No comparar con ECGs anteriores del paciente.',
    ],
    refs: [104, 105, 83],
  },
  {
    id: 'D11',
    group: 'D',
    category: 'oclusion',
    title: 'Hipotermia (Osborn)',
    difficulty: 2,
    vignette: {
      age: 55,
      sex: 'M',
      history:
        'Varón de 55 años encontrado tras exposición prolongada al frío; temperatura central de 29 °C.',
      vitals: 'PA 110/70, FC 45, T 29 °C',
      troponin: 'hs-cTnT 30 ng/L',
    },
    scenario: {
      seed: 411,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 45 },
      conduction: 'normal',
      sources: [{ territory: 'lateral', st: 0.04, refLead: 'V4', shape: 'concave' }],
      beatOverrides: { osbornMv: 0.18 },
      acquisition: { emg: { sigmaMv: 0.08 }, baselineWander: { amplitudeMv: 0.2, hz: 0.3 } },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'La onda J de Osborn es una deflexión positiva justo tras el QRS.',
      'Bradicardia + temblor (artefacto EMG) completan el cuadro.',
      'El recalentamiento resuelve el ECG; no hay oclusión.',
      'La hipotermia produce ondas J de Osborn que se resuelven con el recalentamiento.',
    ],
    pitfalls: [
      'Interpretar la onda J como lesión isquémica.',
      'No medir la temperatura central en el paciente encontrado.',
    ],
    refs: [33, 88],
  },
  {
    id: 'D12',
    group: 'D',
    category: 'oclusion',
    title: 'WPW',
    difficulty: 2,
    vignette: {
      age: 33,
      sex: 'F',
      history: 'Mujer de 33 años con palpitaciones recurrentes paroxísticas desde la adolescencia.',
      vitals: 'PA 115/75, FC 78',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 412,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 78 },
      conduction: 'wpw',
      sources: [],
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'WPW: PR corto + onda delta + T discordante secundaria.',
      'La discordancia por preexcitación no es isquemia.',
      'La historia de palpitaciones orienta el diagnóstico.',
      'La preexcitación WPW produce discordancia secundaria del ST/T que no es isquemia.',
    ],
    pitfalls: [
      'Confundir la onda delta con una onda Q patológica.',
      'Interpretar la discordancia de WPW como OMI.',
    ],
    refs: [33, 19],
  },
  {
    id: 'D13',
    group: 'D',
    category: 'oclusion',
    title: 'Atleta',
    difficulty: 2,
    vignette: {
      age: 22,
      sex: 'M',
      history: 'Varón de 22 años, atleta de resistencia, en chequeo deportivo sin síntomas.',
      vitals: 'PA 110/70, FC 46',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 413,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 46 },
      conduction: 'normal',
      sources: [{ territory: 'anterior', st: 0.1, refLead: 'V3', shape: 'concave' }],
      beatOverrides: { aTScale: 1.2, qtc: 380 },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'hyperacute-t'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'El atleta joven muestra RP con bradicardia y T amplias.',
      'La T grande del atleta es ancha pero no hiperaguda (área/QRS normal).',
      'El contexto de chequeo sin síntomas descarta OMI.',
      'El corazón de atleta muestra bradicardia fisiológica y repolarización precoz.',
    ],
    pitfalls: [
      'Activar el código por un umbral de STE aislado en un asintomático.',
      'No contextualizar la FC baja con el perfil deportivo.',
    ],
    refs: [81, 80],
  },
  {
    id: 'D14',
    group: 'D',
    category: 'oclusion',
    title: 'Inversión LA‑RA',
    difficulty: 1,
    vignette: {
      age: 60,
      sex: 'M',
      history:
        'Varón de 60 años derivado de triage con un primer ECG etiquetado como «alteraciones laterales».',
      vitals: 'PA 130/80, FC 72',
      troponin: 'hs-cTnT < 14 ng/L',
    },
    scenario: {
      seed: 414,
      durationS: 5,
      rhythm: { type: 'sinus', hrBpm: 72 },
      conduction: 'normal',
      sources: [],
      acquisition: { placement: 'la-ra-swap' },
    },
    expected: {
      omi: false,
      activateCathLab: false,
      positiveFindings: [],
      negativeFindings: ['omi-composite', 'stemi-udmi4'],
    },
    angiography: 'no indicada',
    teachingPoints: [
      'LA-RA invertidos: I negativa, aVR positiva, precordiales normales.',
      'El artefacto de electrodos es el mimics más barato de corregir.',
      'Repetir el ECG con colocación correcta antes de decidir.',
      'La inversión de electrodos de miembros es el mimic más frecuente y más barato de corregir.',
    ],
    pitfalls: [
      'Diagnosticar IAM lateral sin verificar la colocación.',
      'No repetir el ECG tras corregir los electrodos.',
    ],
    refs: [98, 106],
  },
];
